### DISCUSSION TITLE
Way of normalizing answers values for template questions

### DISCUSSION THREAD

**Discussion by rszamszur** [copier-org/copier#1009] [Q&A]
Hey @yajo :wave:

I've been wondering what's the official way of normalizing answers values? Currently, I'm using the `when: false` key to sort of post-process prompt value for a given question. Example:

```yaml
# TEMPLATE QUESTIONS
project_name:
  type: str
  help: What's your project name?

# TEMPLATE NONE-CONFIGURABLE DEFAULTS
package_name:
  type: str
  default: "{{ project_name|lower|replace(' ','_')|replace('-','_') }}"
  when: false

```

This is especially useful during templating. Jinja template is much more readable this way. Also it's easier to write `{{package_name}}` rather than `{{ project_name|lower|replace(' ','_')|replace('-','_') }}` in every file/line that needs the variable. Secondly, this gives a mechanism to ensure correct values on the template configuration level.

The problem with using `when:false` for this use case is that, the value will not be updated even if the "parent" answer has changed.  And I know this is currently expected behavior as the docs say:

> If a question is skipped, its answer will be:
> 
> The default value, if you're generating the project for the 1st time.
> The last answer recorded, if you're updating the project.

Is there any other way to normalize answers values, such that it would work with the updates too?

Thanks as always, and have a good one!
