### DISCUSSION TITLE
How do you include a custom jinja filter / macro?

### DISCUSSION THREAD

**Discussion by bgalvao** [copier-org/copier#1128] [Q&A]
I have this function that I cannot find in the [list of built in Jinja filters](https://tedboy.github.io/jinja2/templ14.html)

```python
from os.path import basename

def s3_basename(s3_path) -> str:
    return basename(s3_path)
```

I would like to register `s3_basename` and be able to use it inside the `copier.yml` file.

Is it currently possible? I am asking because so far [in the docs, only the built-in jinja filters are accepted](https://copier.readthedocs.io/en/stable/configuring/#importing-jinja-templates-and-macros).

cc: @gilcardoai

**Comment by yajo** [comment]
You can add jinja extensions: https://copier.readthedocs.io/en/stable/configuring/#jinja_extensions

**Reply by sisp** [reply]
I believe @bgalvao is trying to register custom macros that are defined within the template. AFAIK, this isn't possible at the moment, but I believe we could support it. For instance, how about registering local extensions (that can register macros, filters, etc.) via `copier.yml` like this:

```yaml
_jinja_extensions:
  # Either as a string ...
  - "jinja/extension.py:MyJinjaExtension"
  # ... or as a YAML mapping
  - jinja/extension.py: MyJinjaExtension
```

Here, the path `jinja/extension.py` is part of the template repo (it's just an example, it can be any path to a Python file in that repo). And `MyJinjaExtension` is a subclass of [`jinja2.ext.Extension`](https://jinja.palletsprojects.com/en/3.1.x/extensions/#jinja2.ext.Extension) that is defined in `jinja/extension.py`.

This syntax is somewhat inspired by, e.g., Poetry's [scripts section](https://python-poetry.org/docs/pyproject#scripts).

**Reply by bgalvao** [reply]
I am a noob in Jinja. I will check Jinja extensions by yajo and brb

**Reply by pawamoy** [reply]
@sisp, @bgalvao that's actually what the [`copier-templates-extensions`](https://github.com/copier-org/copier-templates-extensions/#usage) extension allows to do!

```yaml
_jinja_extensions:
- copier_templates_extensions.TemplateExtensionLoader
- extensions/s3basename.py:S3BasenameExtension
```

`S3BasenameExtension` can then be written like this, in `extensions/s3basename.py`:

```python
from os.path import basename
from jinja2.ext import Extension

def s3_basename(s3_path) -> str:
    return basename(s3_path)

class S3BasenameExtension(Extension):
    def __init__(self, environment):
        super().__init__(environment)
        environment.filters["s3_basename"] = s3_basename
```

**Reply by sisp** [reply]
@pawamoy Ahh, I didn't know that. Even better. The only thing is, it needs to be installed separately.

**Reply by bgalvao** [reply]
well, for what I needed, the included ansible extensions had a `basename` kind of function, so it works for me! Thanks!

```yaml
fastapi_s3_model_folder:
    type: str
    help: The name of the subdirectory leaf from the fastapi_bucket_name
    default: "{{ fastapi_bucket_name | basename }}"
    when: false
```
