### DISCUSSION TITLE
construct list of choices via a for loop

### DISCUSSION THREAD

**Discussion by dudicoco** [copier-org/copier#1193] [Q&A]
Hi,

I'm trying to construct the choices list via a jinja for loop:
```yaml
project_type:
  type: str
  choices: ['{% for i in ["one", "two"] %}{{ i }},{% endfor %}']
```

However, this results in a single quoted item in the list:
```sh
project_type
(Use arrow keys)
>> one, two
```

How can the choice be split into a proper list?

**Comment by pawamoy** [comment]
I'm afraid it is not possible to use Jinja in such a way in copier.yml. If the file itself was templated, you could do this:

```yaml
project_type:
  type: str
  choices: [{% for i in ["one", "two"] %}'{{ i }}',{% endfor %}]
```

...but that is not the case: only values are templated. Therefore you cannot use Jinja syntax outside of quoted values.

I'm not sure whether there's a workaround :confused:

**Reply by dudicoco** [reply]
@pawamoy so there is no way to construct dynamic choices with copier?
What about jinja macros/templates/extensions?

**Reply by sisp** [reply]
It might be possible to achieve this using [Jinja native types](https://jinja.palletsprojects.com/en/3.1.x/nativetypes/). This has been mentioned before: https://github.com/copier-org/copier/issues/161#issuecomment-617631999 https://github.com/copier-org/copier/discussions/908#discussioncomment-4805023 However, Copier doesn't support native types at the moment and there's currently no concrete idea how this might be added. But I believe we'd be open to discussing this option. Or perhaps [YAML tags](https://pyyaml.org/wiki/PyYAMLDocumentation#tags) could help, but I'm not sure.

**Reply by dudicoco** [reply]
@sisp I just tried yaml tags and it didn't help.

So I take it that copier is not the right tool for the job if you want dynamic variables? Would cookiecutter be more suitable for that?

**Reply by sisp** [reply]
I don't think Cookiecutter supports dynamic choices either. But it's likely possible to add support to Copier, it just needs a good proposal.

In case your choice items are static but you need to conditionally disable some, Copier supports [conditional choices](https://copier.readthedocs.io/en/v8.0.0/configuring/#advanced-prompt-formatting). Would this help?

**Reply by pawamoy** [reply]
Could you try this?

```yaml
project_type:
  type: str
  choices: !!python/object/apply:str.split ['{% for i in ["one", "two"] %}{{ i }}{% if not loop.last %},{% endif %}{% endfor %}', ',']
```

Or, if PyYAML complains about trying to access `str` directly:

```yaml
project_type:
  type: str
  choices: !!python/object/apply:__builtins__.str.split ['{% for i in ["one", "two"] %}{{ i }}{% if not loop.last %},{% endif %}{% endfor %}', ',']
```

EDIT: hmm I think it won't work, because YAML runs first, then Jinja renders the value... It would need some kind of delayed tag, or a `transform`option, so something Copier only could provide.

**Reply by dudicoco** [reply]
yes both of these did not work

**Reply by pawamoy** [reply]
Thanks for trying!

**Reply by sisp** [reply]
How about extending Copier to support Jinja native types using a custom YAML tag like this?

```yaml
project_type:
  type: str
  choices: !!jinja2-native "[{% for i in ['one', 'two'] %}{{ i }}{% if not loop.last %},{% endif %}{% endfor %}]"
```

The `!!jinja2-native` (tag name open for discussion) YAML tag could inform Copier to use a Jinja `NativeEnvironment` instance instead of the regular environment.

It seems to me that native types could only be useful in `copier.yml` (like here for constructing dynamic choices), all other uses of template syntax seem to be in text files or file/folder names, so rendering as strings is fine there (but correct me if I'm wrong).
