### DISCUSSION TITLE
New strategies for conditional defaults on skipped questions with v8?

### DISCUSSION THREAD

**Discussion by tlambert03** [copier-org/copier#1204] [Q&A]
I have a template that makes heavy use of `when` conditionals along with `defaults` that also depend on prior questions.  For example, take the following config:

```yaml
mode:
  help: "Welcome! Please select a mode:"
  type: str
  default: full
  choices:
    Fully featured: full
    Simple package: simple
    Customize: customize

use_some_feature:
  when: "{{ mode == 'customize' }}"
  type: bool
  help: Would you like to use this specific feature?
  default: "{{ mode != 'simple' }}"
```

Prior to v8 the value of `use_some_feature` would have been:
    - `True` (but not shown) if they selected "Fully featured" mode
    - `False` (but not shown) if they selected "Simple" mode
    - shown as a question if they selected "Customize" mode

I had thought that that was a well-supported feature due to the wording of the docs:

> **when**: Condition that, if false, skips the question.
> If a question is skipped, its answer will be:
>  - The default value, if you're generating the project for the 1st time.
>  - The last answer recorded, if you're updating the project.

As of v8, however, `use_some_feature` will always be False, regardless of whether the use choses "Full" or "Simple" mode.

This change is due to https://github.com/copier-org/copier/pull/1126.  It was raised as a bug in https://github.com/copier-org/copier/issues/1175, but closed and stated as "backwards compatible".  https://github.com/orgs/copier-org/discussions/678#discussioncomment-2822746 is also linked and https://github.com/copier-org/copier/issues/629 is linked for some "ideas".

After some reading though, I've still been unable to come up with a strategy that preserves the behavior mentioned above after v8.

I would greatly appreciate any tips (cc @sisp @pawamoy) for achieving the desired behavior, which again, is to have `use_some_feature` be:

- `True` (but not shown) if they selected "Fully featured" mode
- `False` (but not shown) if they selected "Simple" mode
- shown as a question if they selected "Customize" mode
