### DISCUSSION TITLE
how to use a subdirectory that have a templated name ?

### DISCUSSION THREAD

**Discussion by 12rambau** [copier-org/copier#1322] [Q&A] [answered]
I'm migrating from cookiecutter and I would like to keep the structure of my template:

```
pypackage/
├── copier.yaml
└── {{github_repo_name}}/
    ├── README.rst.jinja
    └── {{_copier_conf.answers_file}}.jinja
```

With the following `copier.yaml`:

```yaml
github_repo_name:
  type: str
  default: "package-skeleton"
  help: "The name of the GitHub repository"
_subdirectory: "{{ github_repo_name }}"
```

But then I get an error as the yaml of the subdirectory is already transformed when copier look for it in the template: 

```
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/copier.vcs.clone.isydjwux/package-skeleton'
```

Is there a workaround ?

**Comment by pawamoy** [comment, marked as answer]
The template subdirectory name cannot be templated. It's just the root folder of the project that will be generated, and the user always chooses the name of the generated project (`copier copy template user_chosen_name`). So my recommendation is to:

1. rename the subdirectory (to something simple like `project` for example)
2. remove the `github_repo_name` question from copier.yml (or use it for something else)

If you have multiple subdirectories though, that a user can choose from, then the question makes sense. The subdirectory names must still not be templated. The question should offer a few choices, and there should be one subdirectory for each choice.

Let me know if anything is unclear, I can try to expand :slightly_smiling_face:

**Comment by 12rambau** [comment]
thanks @pawamoy that's very clear. Just to justify a bit more my use case, a more complete copier.yaml file is: 

```yaml
project_name:
  typr: str
  default: "Package skeleton"
  help: "The name of the project"

github_repo_name:
  type: str
  default: "{{ project_name.lower().replace(' ', '-') }}"
  help: "The name of the GitHub repository"

project_slug:
  type: str
  default: "{{ github_repo_name.lower().replace('-', '_') }}"
  help: "The slug that will be used to name the lib package"
```

allowing the user to fill only the Project name (with space accents and everything) and the template is extracting both the slug and github repo (reused in multiple places afterward like pyproject.toml, doc conf.py etc...).

In what I was doing the user fill it once and for all and propagate to github. From what I understand from your answer, he will need to fill it in the command line as well upfront ?
