### DISCUSSION TITLE
Handling pre-commit config files

### DISCUSSION THREAD

**Discussion by AntoineD** [copier-org/copier#1572] [Q&A]
When a template has a `pre-commit` config file that is updated independently of `copier`, applying `copier update` yields conflicts on the lines that define the hook versions.
Is there a way to prevent copier from updating those lines?

**Comment by sisp** [comment]
Let me confirm I understand your question correctly:

You have a Copier template with a file `.pre-commit-config.yaml` with content similar to this:

```yaml
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.1
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
```

You generate a project and this file is then part of the generated project. Now, `pyupgrade` v3.15.2 gets released and you update the version in the _generated project_ (manually or using some update bot/tool):

```diff
 repos:
   - repo: https://github.com/asottile/pyupgrade
-    rev: v3.15.1
+    rev: v3.15.2
     hooks:
       - id: pyupgrade
         args: [--py38-plus]
```

What about your Copier template? Do you also update the hook version there prior to running `copier update`? I have a suspicion that you're seeing a merge conflict where both resolution options are identical.

Would you mind sharing the snippet of the merge conflict?
