### DISCUSSION TITLE
Access to destination path during the query session

### DISCUSSION THREAD

**Discussion by svenax** [copier-org/copier#1623] [Q&A]
I want to have a template create subfolders based on the basename of the destination folder. Is this already possible somehow? I tried with `_copier_answers._dst_path`, but that is not available until all questions have been answered.

I'd like to be able to do something like this:

```yaml
microservice_directory:
  when: false
  type: str
  default: "{{ _copier_answers._dst_path|basename }}"

microservice_module:
  when: false
  type: str
  default: "{{ microservice_directory|replace('-service', '')|replace('-', '_') }}"
``` 

And then use both variables in my template.
