### DISCUSSION TITLE
Require answer for `multiselect`

### DISCUSSION THREAD

**Discussion by roaldarbol** [copier-org/copier#1694] [Q&A] [answered]
Hi! Have only used `copier` for a short while, so am still learning the ropes. 
Is there a way to require at least one selection when using `multiselect`?

**Comment by sisp** [comment, marked as answer]
You can define a validator:

```yaml
toppings:
  type: str
  help: Select pizza toppings
  multiselect: true
  choices:
    - tomato
    - cheese
    - salami
  default: [tomato]
  validator: >
    {%- if toppings | length < 1 -%}
    You must select at least one topping
    {%- endif -%}
```
