### DISCUSSION TITLE
DRY validators?

### DISCUSSION THREAD

**Discussion by JohnLyman** [copier-org/copier#1754] [Q&A] [answered]
Is it currently possible to make `validator`s generic so they could be used in [YAML anchors](https://support.atlassian.com/bitbucket-cloud/docs/yaml-anchors/) to reduce boilerplate?

For example, in this example in the docs, instead of having to reference `age` in the validator, could it be something like `if self.name ...`? 

```
age:
    type: int
    validator: "{% if age <= 0 %}Must be positive{% endif %}"
```

Thanks for the great project!

**Comment by sisp** [comment]
I think you can achieve reusability of validators using Jinja macros: https://copier.readthedocs.io/en/stable/configuring/#importing-jinja-templates-and-macros See the example in this section that uses a macro for a default value. You should be able to use a macro in a similar way for a validator. WDYT?

**Reply by JohnLyman** [reply]
Thanks for pointing out macros.  I could see how they could be useful.

In the case for validators, it's still a lot of boilerplate because *I think* you'd still have to pass the variable name to the macro?
```yaml
int1:
  validator: "{% from 'positive_int.jinja' import positive_int %}{% if positive_int(int1) %} Must be positive{% endif %}"

int2:
  validator: "{% from 'positive_int.jinja' import positive_int %}{% if positive_int(int2) %}Must be positive{% endif %}"

int3:
  validator: "{% from 'positive_int.jinja' import positive_int %}{% if positive_int(int3) %}Must be positive{% endif %}"
```

vs.

```yaml
int1: 
  validator: &positive_int "{% if self.name <= 0 %}Must be positive{% endif %}"
int2: 
  validator: *positive_int
int3:
  validator: *positive_int
```

Hopefully I'm not missing something obvious here :)
