### DISCUSSION TITLE
Construct list of choices via if-else

### DISCUSSION THREAD

**Discussion by DiegoAz** [copier-org/copier#1789] [Q&A]
Similar to #1193 but using an if-else. I want to load the options in `styles_plugin` based on the response to `stylesheet_language`

```yaml
stylesheet_language:
    type: str
    help: Which stylesheet language do you want to use?
    choices:
        - css
        - sass
    default: css
```
I tried the following
```yaml
styles_plugin:
    type: str
    help: Choose the {{stylesheet_language}} processing plugin
    choices:|-
        {% if stylesheet_language == 'sass' %}":
            - "11tyrocks/eleventy-plugin-sass-lightningcss: lightningcss-sass"
            - "jgarber/eleventy-plugin-sass: jgarber-sass"
        {% else %}:
            - "11tyrocks/eleventy-plugin-lightningcss: lightningcss-css"
            - "jgarber/eleventy-plugin-postcss: postcss-css"
        {% endif %}
```

however, each of the characters of the Jinja code appear as options ({ % if ...)

How can I achieve my goal?
