### DISCUSSION TITLE
How do I copy a templated folder only?

### DISCUSSION THREAD

**Discussion by ferreteleco** [copier-org/copier#1790] [Q&A]
Hi! I'm testing the "exclude functionality of copier to copy a single file or folder, as told in [Copier Documentation](https://copier.readthedocs.io/en/stable/configuring/#exclude ):

`copier copy --exclude '*' --exclude '!file-i-want' ./template ./destination`

So far im using a simple demonstration template:

![image](https://github.com/user-attachments/assets/0885b7ac-f7f0-445f-9b7d-2eae2ee1df0d)

And the related copier.yml:
```yml 
project_name:
type: str
help: What is the project name?
placeholder: demo_project
_min_copier_version: "9.3.1"
_answers_file: .copier-answers.python-project.yml
_subdirectory: template
```

Trying to copy only the file `script.py' is all good with the following:

```bash
copier copy --exclude '*' --exclude '!script.py' . ./demo
```

But I cant get it to work to copy only __init__.py (inside {{project_name}}) or {{project_name}} itself. It does not fail, but gives zero information and does not copy anything. Any tip or hint? 

Thanks in advance!
