### DISCUSSION TITLE
GitHub Action / example GitHub workflow for periodic `copier update` PRs

### DISCUSSION THREAD

**Discussion by pawamoy** [copier-org/copier#1905] [Ideas]
Does anyone have an example of a GitHub workflow that periodically runs `copier update` in a project and sends a PR if there are changes? I'd be interested in setting this up for my multitude of copier-generated projects :slightly_smiling_face: Then such a workflow could be added to the docs, or even be made into a proper GitHub Action (though I suspect the workflow will be very short anyway, so a GitHub Action might be overkill).

**Comment by pawamoy** [comment]
I know Renovate supports Copier (https://docs.renovatebot.com/modules/manager/copier/), but I'd like a standalone solution :slightly_smiling_face: 

Hmm, still maybe a Renovate-based workflow could be added to the docs too!

**Reply by msclock** [reply]
renovate provides the standalone images for us, and our group applies its update mechanism for ss-template such as [ss-cpp](https://github.com/serious-scaffold/ss-cpp/blob/master/.github/workflows/renovate.yml) to detect changes from upstream ss-cmake and ss-license.

See https://github.com/serious-scaffold/ss-cpp/pull/436, https://github.com/serious-scaffold/ss-cpp/pull/435

**Reply by pawamoy** [reply]
Thanks for sharing! I see committed merge conflicts in the second PR, I suppose you'll either suggest fixups in the PR or close it and handle the update manually?

**Reply by msclock** [reply]
> committed merge conflicts in the second PR

because the update is under the subdir `template`. `skip_if_exists` in the parent template `ss-cmake` didn't work. See #1894. It needs manual resolution on conflicts.

**Comment by pawamoy** [comment]
A bit more complex than I anticipated:

```yaml
name: copier

on: push
  # schedule:
  # - cron: "0 18 * * 4"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Setup uv
      uses: astral-sh/setup-uv@v1
      with:
        enable-cache: true
    - name: Checkout new branch
      run: |
        git branch -D copier-update || true
        git push origin --delete copier-update || true
        git checkout -b copier-update
    - name: Run Copier update
      run: |
        uvx --from copier==9.3.* --with copier-templates-extensions copier update --trust --skip-answered --defaults
        git diff --name-only --diff-filter=U | while read -r file; do git checkout --theirs "$file"; done
    - name: Commit changes and create PR
      run: |
        git config --global user.name "Timothée Mazzucotelli"
        git config --global user.email "pawamoy@users.noreply.github.com"
        git add -A .
        if git commit -am "chore: Template upgrade"; then \
          git push --set-upstream origin copier-update; \
          gh pr create -B main -H copier-update --title 'chore: Template upgrade' --body ''; \
        fi
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**And conflict resolution doesn't work yet because of [this issue](https://github.com/copier-org/copier/issues/1833#issuecomment-2562694770).**
