### DISCUSSION TITLE
lint setup for jinja

### DISCUSSION THREAD

**Discussion by up-stevesloan** [copier-org/copier#1935] [Q&A]
Thanks for the awesome tool (and maintenance thereof)!

I've been developing my template repo using `.jinja` versions of the files I want copied to the project repos.  However, I don't find out that there are jinja syntax issues until I copy.  I'm hoping to set up a linter so as to discover these problems prior to committing to my template - what are folks using for this?

Ideally I'd also be able to lint the jinja templates against the questions in copier.yml to ensure nothing's misspelled.

**Comment by pawamoy** [comment]
You could try https://pypi.org/project/djlint/ and similar projects as a first step :slightly_smiling_face:

**Reply by up-stevesloan** [reply]
Thanks - I went down that road and was surprised at all the unimportant things it errored about, which made me curious what others had tried.  I will start paring down the checks it runs now...

**Reply by pawamoy** [reply]
I have tried a few linters/formatters for Jinja but never found one I was satisfied with :confused: I do have unit tests for my template though, which will catch any syntax error, or mistakes in rendering that prevents the generated projects from working as expected :slightly_smiling_face:

**Reply by up-stevesloan** [reply]
Thanks, yes, unfortunately I'm coming to the same conclusion.  I just added an error into the jinja syntax in one template file and `djlint` did not catch it.  Plus it appears there's no way to have it check against the questions.

Thanks for the quick response @pawamoy !

**Reply by up-stevesloan** [reply]
I did end up having some luck with `djlint` - it will catch some errors.  If anyone's interested, here's my `pyproject.toml` config:
```toml
[tool.djlint]
profile="jinja"
extension = ".jinja"
ignore = "H001,H002,H003,H004,H005,H006,H007,H008,H009,H010,H011,H012,H013,H014,H015,H016,H017,H018,H019,H020,H021,H022,H023,H024,H025" # suppress HTML issues
quiet = false
verbose = true
```
