### DISCUSSION TITLE
How to rename variables while maintaining compatibility?

### DISCUSSION THREAD

**Discussion by 34j** [copier-org/copier#1980] [Q&A] [answered]
I would like to follow #1940 and change the variable name `full_name` [that was already in use](https://github.com/browniebroke/pypackage-template/blob/665c4e2cffac7c88473c567a6def290fa1a80e65/copier.yml#L2) to `user_name`, but I don't know the correct way to do this while maintaining compatibility (i.e. avoiding to retyping the name when `copier update`). Perhaps something like this?

```yaml
full_name:
  type: str
  when: false
  default: ""

user_name:
  type: str
  default: {{ full_name }}
```
