### DISCUSSION TITLE
Using `when` with a command's exit status

### DISCUSSION THREAD

**Discussion by wgordon17** [copier-org/copier#2073] [Q&A] [answered]
Is it possible, especially with Tasks, to set `when` to be a command, and the task runs based on the exit status of the command? Where a status of `0 == true`, i.e., if the `when` command _succeeds_ then the task is skipped.

E.g.,

```yaml
_tasks:
  - command: "git init"
    when: "! git log -1 --pretty=oneline || false"
```

In my example, `git init` will _only_ run if a git repository doesn't already exist (`git log -1 --pretty=oneline` returns `true` for an existing repo and `false`, the exit code is inverted with `!` such that `when` is `true` if `git log -1 --pretty=oneline` is false).

If this isn't already possible, perhaps it could be possible to implement something like `when_command`?

**Comment by sisp** [comment, marked as answer]
How about using, e.g., [`jinja2-shell-extension`](https://github.com/metwork-framework/jinja2_shell_extension/) and calling your status command in a `when` template?

```yaml
_jinja_extensions:
  - jinja2_shell_extension.ShellExtension

_tasks:
  - command: "git init"
    when: "{{ 'git log -1 --pretty=oneline && echo \"false\" || echo \"true\"' | shell }}"
```

(Disclaimer: I haven't tested this template, but this or something similar should work.)

Or you could register your own tiny Jinja2 extension that directly translates a shell exit code to `"true"`/`"false"`. See, e.g., https://github.com/pawamoy/copier-uv/blob/main/extensions.py + https://github.com/pawamoy/copier-uv/blob/main/copier.yml#L11-L14.

**Reply by wgordon17** [reply]
Ohh, that's nifty! Let me give that a try (wow, what _won't_ they make a Jinja extension for?? 😅)

**Reply by wgordon17** [reply]
~For anyone else coming across this, I _technically_ didn't try the `jinja2-shell-extension` extension (or the similar [`jinja2-shell`](https://github.com/34j/jinja2-shell) either) because neither were available as Nix packages. **But**, I was able to get this working with [`jinja2-git`](https://github.com/wemake-services/jinja2-git).~

```yaml
_jinja_extensions:
    - jinja2_git.GitExtension
_tasks:
  - command: "git init"
    when: "{% if gitcommit %}false{% else %}true{% endif %}"
```

Edit: Ok, so this turns out to _not_ work the way I expected. Once I actually started testing this for real, it was just throwing errors or silenting giving the wrong output.

**Reply by wgordon17** [reply]
Alrighty, so after not finding _exactly_ what I was looking for, I went off and _built it_ (because...why not ¯\\\_(ツ)_/¯ ).

The Jinja extension is available here: https://github.com/gordon-code/jinja2-git-dir?tab=readme-ov-file#copier
and even includes a section to how to use/apply within Copier. Hope this helps anyone else who might stumble across it!

```yaml
_jinja_extensions:
    - jinja2_git_dir.GitDirectoryExtension
_tasks:
  - command: "git init"
    when: "{{ _copier_conf.dst_path | realpath | gitdir is false }}"
  - command: "git commit -am 'initial commit'"
    when: "{{ _copier_conf.dst_path | realpath | emptygit is true }}"
  - command: "git commit -am 'template update applied'"
    when: "{{ _copier_conf.dst_path | realpath | emptygit is false }}"
```
