### DISCUSSION TITLE
User settings and defaults not working

### DISCUSSION THREAD

**Discussion by MrTango** [copier-org/copier#2131] [Q&A] [answered]
Hello, i want to use the settings.yml in my user home on a Debian system.
But what ever i do it does not take my settings from my settings.yml file.

My file is located in: `/home/maik/.config/copier/settings.yml` and i have set the project_name variable in there, as a test.
But when i run my template, the variable is not filled as default.

Also the trust settings are not working, i still have to add --trust to the call.

My settings file looks like this:

```yml
defaults:
  user_name: "MrTango"
  user_email: md@derico.de
  github_user: "MrTango"
  gitlab_user: "MrTango78"
  project_name: "test-project"
trust:
  - https://github.com/MrTango
```

what do i miss here?
