### DISCUSSION TITLE
conditional include tag

### DISCUSSION THREAD

**Discussion by idkman23** [copier-org/copier#2201] [Q&A] [answered]
Is this possible with copier? I'd like to include other yaml files based on the `cloud` choice:

```
cloud:
    type: str
    help: Which cloud provider would you like to use?
    choices:
        - azure
        - aws
        - oci

# this doesn't work:
# ---
# !include "{% if cloud == 'oci' %} copier/oci/*.yaml {% endif %}"
# ---

```

I know about the `when` option but I'd have to include that in all of the questions which creates a lot of repetition.
