### DISCUSSION TITLE
Multiple lines

### DISCUSSION THREAD

**Discussion by Honest-Objections** [copier-org/copier#415] [Q&A] [answered]
How do you take multiline input?

For example: 
```yaml
project_description: 
  type: str
  multiline: true
  help: An introduction to your project, for the README
```

Still only takes a single line of input when prompted on the command line and the [docs](https://copier.readthedocs.io/en/latest/configuring/#advanced-prompt-formatting) are very vague
