### DISCUSSION TITLE
Multiple choice type

### DISCUSSION THREAD

**Discussion by Honest-Objections** [copier-org/copier#419] [Ideas]
It would be great to have a multiple choice type, for when you have listed choices. Example:

```yaml

ice_cream_toppings:
  type: multiple_choice
  help: Which toppings do you want on your ice cream?
  choices:
    - rainbow_sprinkles
    - chocolate_sauce
    - chocolate_flake
```

This would then pass through a list to your Jinja:
```
ice_cream_toppings: [ 'chocolate_flake' ]
```
