### DISCUSSION TITLE
Nested questions / includes

### DISCUSSION THREAD

**Discussion by Honest-Objections** [copier-org/copier#420] [Ideas]
It's not uncommon to need/template for loops. This use cases is only handled for a predefined amount at the moment using `!include loop_questions.yaml` 

However the ability to do something such as the following would make copier far more powerful:

```yaml
# customer_order.yaml

name:
  help: The customers name
  type: str
  
ice_cream_quantity:
  help: How many ice creams would you like to buy?
  type: int

ice_cream_orders:
  type: include ice_cream_order.yaml
  value: "{{ ice_cream_quantity }}"
```

```yaml
# ice_cream_order.yaml

type:
  choices:
    - lollipop
    - flake
    - magnum

serviette:
  - type: bool
  - help: Do you want a napkin with this order?

# etc etc
```

This would then populate `ice_cream_orders` as a list of objects: `ice_cream_orders: [ {type: magnum, servette: False } ]`. The user would be prompted to fill out the `ice_cream_orders` questions for the amount of times they answered in `ice_cream_quantity`

I'm not set on the implementation at all, but this would make copier essentially feature complete without extension as far as I'm concerned. The ability to use a git module for the include would be a great bonus

**Comment by yajo** [comment]
What would be a use case for this?

**Reply by Honest-Objections** [reply]
As above, I suppose. In my instance I'm looking to create an XML file through the `copier.yaml`. This file can contain multiple elements that are the same and it can vary each time a new project is made, so the ability to `!include` multiple times means everything can be handled by copier without extension

As an aside, when using `git-submodules`, is it expected to only contain question yaml? As I would love to have templated files with the questions in a separate repo but don't currently understand how that model is supposed to work

Thanks for your hard work on `copier`, I can see it being a fantastic tool as it matures! (And if course it is already)

**Reply by yajo** [reply]
A question can have a YAML or JSON answer. That can be a list of dicts for example, which can be enough for your use case if I'm understanding it correctly.

However, how to know that the YAML is being answered correctly? The only check we have today (in master) is syntax. When #398 is fixed, you will be allowed to more creativity on validations.

The solution you propose is probably never going to be done, because `copier.yaml` is expected to be static, as it only contains config and questions. The fact you compose it from several parts doesn't make it dynamic, just static but split.

**Reply by Honest-Objections** [reply]
Yeah, I had initially considered that, however you lose the user interface and as there are types/enums in the XML it means you can't inform the user and that's quite sad! So to better explain the whole picture: 

* We have lots of different types of projects which all output to a tool
* Each project type will ideally have a `copier` template 
* There is a submodule `copier` template to create the XML for the tool they all output for 

So I would like to have the submodule be like so: 

```yaml
# copier.yml
project_name:
  help: The name of the project 
  type: str

artifacts: 
  type: sub_questions
  location: copier_artifacts.yml
  help: How many artifacts do you want to import?
```

```yaml
# artifacts.yaml

type:
  choices:
    - BUILD_FILE
    - CONFIG_FILE
    - OTHER
 
location:
  type: str
  help: Path to artifact
```

This would then ideally produce something to the effect of (for the `artifacts` section):
![image](https://user-images.githubusercontent.com/11096663/124174501-5d50cc00-daa4-11eb-9d96-0f65f37cc655.png)

With the template being able to look similar to: 
```xml
<product>
  <name>{{ project_name.upper() }}</name>
  <artifacts>
  {% for artifact in artifacts %}
    <artifact>
      <location>{{ artifact.location }}</location>
      <type>{{ artifact.type }}</type>
    </artifact>
  {% endfor %}
  </artifacts>
</product>
```

So the user gets prompted to move on at the end of each loop. While `YAML` input could be explained in the help section of a single artifacts and then adding a complex validation, it wouldn't be very user friendly at all. If the type can be a separate question set, it at least keeps everything separate and the logic fairly simple

If you can help come up with a solution you like, I'm more than happy to contribute to make it happen!

**Reply by yajo** [reply]
If you want to contribute it, I think that the simplest approach would be to add a new key to the question format: `loops`. Its value should be templatable, just like any other value in the `copier.yaml` file. It would look like this:

```yaml
artifacts_num:
  type: int
  help: How many artifacts do you want to build?

type:
  type: str
  choices:
    - BUILD_FILE
    - CONFIG_FILE
    - OTHER
  loops: "{{ artifacts_num }}"

location:
  type: str
  help: Path to artifact
  loops: "{{ artifacts_num }}"
```

It would produce these sample answers:

```yaml
artifacts_num: 2
type:
  - BUILD_FILE
  - CONFIG_FILE
location:
  - location for 1st artifact
  - location for 2nd artifact
```

And you could iterate in your template based on the assumption than both answers would be lists with same length because both would have the same value for `loops` (or you could use the `artifacts_num` variable to know the desired loop length beforehand).
