### DISCUSSION TITLE
A 'required' option to ensure empty strings aren't provided

### DISCUSSION THREAD

**Discussion by Honest-Objections** [copier-org/copier#422] [Ideas]
If you set the `type` to choices, the user must pick one before proceeding. Unless it's been changed since the version I'm using, type `str` can be (very rightly) empty. However it would be great to enforce that a not null answer is given:

```yaml
name_of_ice_cream:
  type: str
  help: The name of your new ice cream, you invented 
  required: True
```

The user must then provide a not None answer before they can continue

**Comment by yajo** [comment]
If you don't provide a default value, the answer is required, isn't it?

**Reply by Honest-Objections** [reply]
I've tried again in version `5.1` I believe, and if you don't provide a `default`, `None` is used as the default, so the user can always get past.

So I suppose this is perhaps more of a bug report? Although I do think it should be an option to skip as it is at the moment!

**Reply by yajo** [reply]
Please could you check on master? v5 is kinda frozen and it won't get any more fixes. Master is way more cool (although unstable still).

**Reply by Honest-Objections** [reply]
Checking out master, the bug has certainly been fixed where default is automatically assigned to `None` when not provided! But you can of course skip over it if you want... But! #398, which you pointed me to in a different discussion meets the requirements:

```yaml
project_name:
  type: str
  description: The project name
  validate: .*\S.*
```

So another question answered: feature available in `6` 🥳
