### DISCUSSION TITLE
Choices in selection from multiple subdirectory template

### DISCUSSION THREAD

**Discussion by Shreyanns** [copier-org/copier#505] [Q&A]
I have a requirement where I wanted to keep multiple templates as subdirectories and ask users to select which template he wants. Is this possible in copier?

**Comment by yajo** [comment]
Yes, it would be something like this:

```yaml
# copier.yaml
_subdirectory: "{{ chosen_subdir }}"
chosen_subdir:
  choices:
    - dir1
    - dir2
```
