### DISCUSSION TITLE
Is there a way to define variables in copier.yml?

### DISCUSSION THREAD

**Discussion by eyllanesc** [copier-org/copier#545] [Q&A]
In my particular case I have the following copier.yml:

```yaml
github_user:
  type: str

github_repo:
  type: str
```

And in various parts of my .jinja files I do the following: 

```jinja
"Changelog" = "https://github.com/{{ github_user }}/{{ github_repo }}/releases"
```

```jinja
"Bug Tracker" = "https://github.com/{{ github_user }}/{{ github_repo }}/issues"
```

```jinja
"Issues" = "https://github.com/{{ github_user }}/{{ github_repo }}/issues"
```
```jinja
"Discussions" = "https://github.com/{{ github_user }}/{{ github_repo }}/discussions"
```

I want to define a variable in copier.yml that is the same as "questions":

```jinja
{%- set repository = "https://github.com/" ~ github_user + "/" ~ github_repo -%}
```

And then use: 

```jinja
"Changelog" = "{{ repository }}/releases"
```

```jinja
"Bug Tracker" = "{{ repository }}/issues"
```

```jinja
"Issues" = "{{ repository }}/issues"
```
```jinja
"Discussions" = "{{ repository }}/discussions"
```

Can this be done in copier?

**Comment by pawamoy** [comment]
You could use my extension, https://github.com/pawamoy/copier-templates-extensions, particularly the Context Hook extension, to augment your context (in this case adding the `repository` variable).

**Reply by eyllanesc** [reply]
@pawamoy  IMHO a good workaround but it would be great if copier natively supports that feature, for example I have tested that if a variable starts with `_` then it is not shown in the command prompt so maybe if copier collects the variables that start with `_` as global variables or create a section: 

```yaml
_globals:
    repository : "https://github.com/{{ github_user }}/{{  github_repo  }}"
```

and then can be used in templates like: 

```jinja
{{  repository  }}
```

OR

```jinja
{{  globals.repository  }}
```

The advantage of this feature is that you have a cleaner template.

**Reply by pawamoy** [reply]
Yeah I had a somewhat similar feature request: https://github.com/copier-org/copier/issues/229.
Since I had found a workaround, and then later created the copier-templates-extensions loader and context hook, it did not go further.

I agree that some simple, native way to alter the context would be very useful. I just worry that allowing to do that in copier.yml would not be very powerful, as you'd have to do everything within Jinja's engine limits.

**Reply by pawamoy** [reply]
Anyway, that would be fine I think. It stays kinda language agnostic and if you need something more powerful, there's always my extension loader hackery :slightly_smiling_face:

**Reply by eyllanesc** [reply]
@pawamoy Exactly, for trivial matters like declaring a variable I don't see the logic of implementing code in python necessarily, it should be implemented in copier.yml, that would not eliminate the use of your extension since in copier.yml you can only do basic things then your extension could be used for more interesting things. 

I was thinking of taking advantage of the fact that the statements that start with "_" are not asked to the user, so it should only be evaluated using the previous information and added as variables to the context. Something like: 

```yml
github_user:
  type: str

github_repo:
  type: str

_github_repository : "https://github.com/{{ github_user }}/{{ github_repo }}"
```

And then it can be used in the templates: 

```jinja
{{ github_repository }}
```
what do you think ? 

cc: @Yajo

**Reply by pawamoy** [reply]
Such names could clash with actual Copier configuration. I'd prefer a way to declare them as questions, without Copier prompting them to the user.

**Reply by eyllanesc** [reply]
One possible solution is for Copier to have a blacklist that they can't use as variables: 

- _subdirectory,
- _templates_suffix,
- _skip_if_exists,
- _tasks, etc.

Another solution is that a prefix (or suffix) can be used

**Reply by pawamoy** [reply]
Yes, I think I like one of your suggestions: `_globals: {}`. Copier could read it, render each item, and inject them in the context, at the top-level (not under a `_globals` key). Could also be named `_context` or something similar.

**Reply by eyllanesc** [reply]
I loved that option but I see a drawback, for example why limit that variable to templates since it could also be used in the copier.yml itself, something like: 

```yml
github_user:
  type: str

github_repo:
  type: str

_github_repository : "https://github.com/{{ github_user }}/{{ github_repo }}"

foo:
  type: str
  default: "foo {{ github_repository }}"
```

The option to create an attribute that indicates that the user is not asked also seems valid to me.

**Reply by pawamoy** [reply]
You make a good point. Repeating stuff in copier.yml is not fun either. Then I'm back to my initial request for a `hidden`-like boolean flag on questions :sweat_smile:
Or maybe an option to directly say "don't prompt this, and use this value":

```yaml
github_user:
  type: str

github_repo:
  type: str

github_repository:
  const: "https://github.com/{{ github_user }}/{{ github_repo }}"

foo:
  type: str
  default: "foo {{ github_repository }}"
```
