### DISCUSSION TITLE
Dumb question, why is my when condition not working?

### DISCUSSION THREAD

**Discussion by HatDan255** [copier-org/copier#659] [Q&A] [answered]
Just a basic question, for some reason the when condition doesn't work for me tried several ways

```
add_stuff:
    type: bool
    help: Add stuff?
    default: false
stuff_name:
    type: str
    default: temporary
    when: "[[ add_stuff ]]"
```
also tried:
when: "[* if add_stuff== true *]"
when: "[[ if add_stuff== true ]]"
when: "[[ if add_stuff== True ]]"
when: add_stuff

![image](https://user-images.githubusercontent.com/104925307/166742231-b9a5aecb-adb1-4557-a4ac-c342b00b58ab.png)
