### DISCUSSION TITLE
How to delete conditionally-added files when changing answer?

### DISCUSSION THREAD

**Discussion by EBoisseauSierra** [copier-org/copier#684] [Q&A]
I am adding files conditionally to my instance, as per [the docs](https://copier.readthedocs.io/en/stable/configuring/#conditional-files-and-directories):
```
.
├── CHANGELOG.md
├── {{_copier_conf.answers_file}}.jinja
├── copier.yaml
└── data
    └── {% if include_data %}my_data.csv{% endif %}.jinja
```

with `copier.yaml` like:

```yaml
include_data:
  help: Do you want to include data?
  type: bool
  default: false
```

**Question:** Say I first said Yes to including data when running `copier`, how to _delete_ `my_data.csv`  from my instantiated repo if I run `copier` again on it (e.g., for an update) and answer No this time?
