### DISCUSSION TITLE
Conditional adding/removing of choices

### DISCUSSION THREAD

**Discussion by MaciejPatro** [copier-org/copier#704] [Q&A]
Hello

What is the intended way to handle adding/removing choices based on previously answered prompt?

The example is I want to let user have more options of unit testing frameworks based on C++ standard the project is supposed to support:

I've solved this problem in this way:
```yml
cpp_standard:
  type: int
  default: 17
  choices:
    Cpp23: 23
    Cpp20: 20
    Cpp17: 17
    Cpp14: 14
    Cpp11: 11
    Cpp98: 0
    
unit_testing_98:
  type: str
  default: null
  when: "{{ cpp_standard == 0 }}"
  choices:
    - GTest
    - None

unit_testing_11:
  type: str
  default: null
  when: "{{ cpp_standard > 0 }}"
  choices:
    - doctest
    - GTest
    - None
```

and using context hook I populate `unit_testing` with the correct choice.

Is there a smarter way of handling "conditional" choices? Because if I would like to introduce support for C++17 or newer unit testing framework I would need to again add another parameter and complicate the `copier.yaml` file even more.

**Comment by yajo** [comment]
There's really not a much better option available right now 🤔 

This is the 1st time I see this use case.

I guess #698 will help you here, being able to validate an answer and provide feedback on why it cannot be chosen.

Also we could add support for [the `disabled` property of `Choice`](https://questionary.readthedocs.io/en/stable/pages/api_reference.html#questionary.Choice).

**Reply by MaciejPatro** [reply]
Thank you for quick answer!

I would guess for now I will keep the solution I came up with.

The goal for me was to ensure that users can't make a wrong choice in the first place. 
Failing to generate a template for choosing an option that was given to the user seems as bad design of this particular template - for that reason I think validation is not really a good use-case here. 

The `disabled` property seems interesting as this not only "saves" user from failing - but also allows to inform them what kind of configuration they need, to use the disabled choice (if for any reason they want it).

Maybe I will look in the weekend if the implementation is not too complicated.

**Comment by pawamoy** [comment]
Maybe we could remove empty choices from the list?

```yaml
unit_testing:
  type: str
  default: null
  choices:
    - "{% if cpp_standard > 0 %}doctest{% endif %}"
    - GTest
    - None
```

Just like we don't create files/dirs with empty names?
