### DISCUSSION TITLE
Support Multiple Templates per Repository

### DISCUSSION THREAD

**Discussion by BrutalSimplicity** [copier-org/copier#855] [Ideas]
I would like for `copier` to support multiple templates in a given repository by allowing the subdirectory of the repository to be specified with the vcs ref, and supporting updates by filtering commit history based on the subdirectory and a user-specified suffix/prefix for tags.

Alternatively, I can continue to use single repo per template approach that makes template management more difficult on the user and developer.

**Comment by BrutalSimplicity** [comment]
I've seen this workaround, https://copier.readthedocs.io/en/stable/configuring/#subdirectory, but I don't believe that will support the use case of having different questions per template. Unless it's possible to pull in questions from each subdirectory. If so, that would be 💯

**Reply by bittner** [reply]
To showcase a real use case, I have a Python TDD tooling and education project that provides [project examples](https://github.com/painless-software/python-cli-test-helpers/tree/main/examples) in a subfolder. Since developers are lazy I want them to be able to generate one of those "flavors" in the subfolder directly off GitHub, i.e. avoiding to have to clone the project first. Quite a few developers would certainly stop here otherwise for trying the project out.

The user experience I'm after is a simple, intuitive one-liner, e.g.

```
copier https://github.com/foo/bar examples/one cli-example
```

Note that there is now an explanation for the [_"1 template = 1 Git repository"_ recommendation](https://github.com/painless-software/python-cli-test-helpers/tree/main/examples) in the documentation, along with a suggested solution.

> With this questions file and this directory structure, the user will be prompted which Python engine to use, and the project will be generated using the subdirectory whose name matches the answer from the user:

This sounds promising! I'm curious whether it has my use case covered. :eyes: :robot:

**Comment by BrutalSimplicity** [comment]
nvm, it's in the docs, https://copier.readthedocs.io/en/stable/configuring/#include-other-yaml-files. I think I can work with the combination of those two options.

**Comment by mshafer-NI** [comment]
@BrutalSimplicity, if you figure out a working example, I would be interested in seeing it.

**Comment by BrutalSimplicity** [comment]
Well, I can open this back up. Do you mean the original support in the ticket, or a setup that the configuration supports?

**Comment by mshafer-NI** [comment]
An example layout, I'm interested doing something similar.

**Comment by BrutalSimplicity** [comment]
Hmm, ok. I assume you've seen this.

<img width="767" alt="image" src="https://user-images.githubusercontent.com/5298126/198733232-441d8e85-d03a-4cab-b243-7601a6b145a2.png">

**Comment by mshafer-NI** [comment]
Yes, I played with putting extra `copier.yml` files in the `_subdirectory`, but didn't seem to get anywhere with that.

**Comment by mshafer-NI** [comment]
(I am currently including a handful of files in the top level `copier.yml` to separate out my questions and each question does a when based on the `_subdirectory` parameter); but this has the downside of everything winding up in every answers file.

**Comment by yajo** [comment]
Maybe yaml anchors can help you reducing repetition.

**Comment by icj217** [comment]
I've come up with a somewhat feasible approach to multiple templates in a repository (possible once a release is created that includes [this merged PR](https://github.com/copier-org/copier/pull/1027))

Basically, the repo will contain a single `copier.yml` file containing a single required question named `template` indicating the template to use, and then template-specific questions below it that are conditional.

```yaml
# copier.yml

# Save answers to file namespaced by selected template
_answers_file: ".copier-answers.{{ template }}.yml"
# Store each template under separate subdirectory
_subdirectory: "{{ template }}"
# Don't include the README
_exclude:
  - README.md

template:
  type: str
  choices:
    - foo
    - bar
    - baz

# foo questions

foo_question1:
  type: str
  when: &foo
    "{{ template == 'foo' }}"

foo_question2:
  type: str
  when: *foo

# bar questions

bar_question1:
  type: str
  when: &bar
    "{{ template == 'bar' }}"

bar_question2:
  type: str
  when: *bar

# baz questions

baz_question1:
  type: str
  when: &baz
    "{{ template == 'baz' }}"

baz_question2:
  type: str
  when: *baz
```
For each choice in `template`, you create a separate directory with that name containing your template files + and answers file i.e.
```
copier.yml
foo/
  < files >
  {{_copier_conf.answers_file}}.jinja
bar/
  < files >
  {{_copier_conf.answers_file}}.jinja
baz/
  < files >
  {{_copier_conf.answers_file}}.jinja
```

This allows you to choose from multiple templates stored in the same repository and ensure that each template choice saves its answers to its own namespaced answers file e.g. `.copier-answers.foo.yml`
