### DISCUSSION TITLE
regex_search in validation

### DISCUSSION THREAD

**Discussion by mvanholsteijn** [copier-org/copier#892] [Q&A] [answered]
In Issue https://github.com/copier-org/copier/issues/398, it is suggested that you can use  jinja2 ansible filters to use a regex expression in a validation, but no example is given.

The request in the issue thread was to ask a question here on the forum. So here it is: can you given an example of using a regex in a validation?

**Comment by mvanholsteijn** [comment, marked as answer]
So, I figured it out. Here is an example:

```yaml
resource_name:
  type: str
  help: The name of your custom resource?
  validator: >-
    {% if not (resource_name | regex_search('^Custom::[A-Z][a-zA-Z0-9]+$')) %}
    Must be a CloudFormation custom type name, eg Custom::Custom.
    {% endif %}

```
