### DISCUSSION TITLE
Correct use of partials?

### DISCUSSION THREAD

**Discussion by adepretis** [copier-org/copier#960] [Q&A]
The documentation states

> The copier.yml file supports multiple documents. When found, they are merged (not deeply merged; just merged) and the latest one defined has priority.
>
> It also supports using the !include tag to include other configurations from elsewhere.
>
> These two features, combined, allow you to reuse common partial sections from your templates.

I'd like to include partials at a specific point in the questionnaire. With the mentioned `!include` and YAMLs support for multiple documents this looks like this:

```
question1:
  type: str
  help: integrate into environment X

---
!include environments/myenv_x/network.yml
---

question2:
  type: str
  help: integrate into environment Y

---
!include environments/myenv_y/network.yml
---

question3:
  type: str
  help: integrate into environment Z

---
!include environments/myenv_z/network.yml
---
```

This works as it should but it feels weird to everytime create a new document. Would you deem this correct, do I care to much about documents?

Wouldn't something like [pyyaml-include](https://github.com/tanbro/pyyaml-include) make more sense and also provide nested includes on top?

```
question1:
  type: str
  help: integrate into environment X

!include environments/myenv_x/network.yml

question3:
  type: str
  help: some choices
  choices: !include common/reused_choices.yml
```
