### ISSUE TITLE
Add support for conditional choices

### ISSUE THREAD

**Issue by sisp** [copier-org/copier#1001]
**Is your feature request related to a problem? Please describe.**
Sometimes, there is a dependency between questions where the validity of an answer to a choice question depends on the answer to a previous question. Currently, Copier doesn't support enforcing constraints on choice questions.

**Describe the solution you'd like**
I'd like to be able to make a choice item conditional, so that only valid choices are presented in interactive mode and an invalid answer would raise a validation error in CLI/API mode.

I believe conditional choice items could be implemented like this:

```yaml
# List syntax
question_with_list_choices:
  choices:
    - "{% if <condition-1> %}choice-1{% endif %}"
    - "{% if <condition-2> %}choice-2{% endif %}"
    - ...

# Dict syntax
question_with_dict_choices:
  choices:
    "{% if <condition-1> %}choice-1{% endif %}": null
    "{% if <condition-2> %}choice-2{% endif %}": null

# Tuple syntax
question_with_tuple_choices:
  choices:
    - ["{% if <condition-1> %}choice-1{% endif %}", null]
    - ["{% if <condition-2> %}choice-2{% endif %}": null]
```

Whenever (a) the list item is an empty string or (b) the dict key is an empty string or (c) the first element in the tuple is an empty string, the choice is ignored. Of course, a non-`null` value is possible for the dict and tuple syntax, but I wanted to keep the example consistent.

Copier currently allows an empty choice:

```yaml
question_with_list_choices:
  choices:
    - ""
```

```shell
$ copier $tpl $dst
🎤 question_with_list_choices
   (Use arrow keys)
 »
```

However, I don't think empty choices make much sense, so it should be fine to ignore them.

**Describe alternatives you've considered**
Instead of omitting invalid choices, it might be useful to show all choices and validate them, so that invalid choices show an error when selected. Regarding UX, I think omitting invalid choices is preferable to showing errors though.

**Additional context**
Related to #996.

**Comment by yajo** [comment]
https://questionary.readthedocs.io/en/stable/pages/api_reference.html?highlight=choice#questionary.Choice

Could be enough a templated "disabled" attribute?

**Comment by yajo** [comment]
After thinking about it, I see we should implement this last comment instead. The solution would need using the dict or tuple style, when the value would be a dict too. Example: 

```yaml
woohoo: "😀"

eeey:
  type: str
  choices: 
    This is available: wassup?
    This isn't always: 
      value: can't touch this
      available:  &check "{{ woohoo == '😀' }}"
    Reusability!:
      value: null # becomes "Reusability!"
      available: *check 
```

The fact some choices appear as disabled helps to understand that they're invalid, thus fuxing better the use case of #996.

The fact disabled asks for a bool helps reusing it with yaml anchors and making it a bit shorter. 

This would open the door for supporting separators and shortcuts too.

**Comment by sisp** [comment]
Sounds good. :+1: Just one question: What do you think about calling the field `when` instead of `available`? `when` is used for questions, too, so the naming is more consistent and familiar, and `when` in questions also has a bool-like value type.

**Comment by sisp** [comment]
> Did that really work? How was it rendered on TUI?

Yes. It is rendered like this:

```
🎤 eeey (yaml)                                                                                                                                                          
   (Use arrow keys)
 » This is available
```

And the answer in `.copier-answers.yml` looks like this:

```yaml
eeey:
    key1: 1
    key2: two
```

Shall I add a test case to cover this case and avoid regression in the future?

But the problem remains that when a choice value is a YAML/JSON mapping, it is indistinguishable from the extended syntax you suggested. Off the top of my head, the only safe alternative I see is to always use your suggested syntax for dict-style choices where `available` (or now `when`) is an optional field, i.e.:

```diff
 woohoo: "😀"

 eeey:
   type: str
   choices: 
-    This is available: wassup?
+    This is available:
+      value: wassup?
     This isn't always: 
       value: can't touch this
       when:  &check "{{ woohoo == '😀' }}"
     Reusability!:
       value: null # becomes "Reusability!"
       when: *check 
```

But that's a breaking change. :see_no_evil:

> Seems good to me.

:ok_hand:
