### ISSUE TITLE
Disallow duplicate choices

### ISSUE THREAD

**Issue by sisp** [copier-org/copier#1002]
**Describe the problem**
Copier currently allows duplicate choices without raising an error, but I don't think duplicated choices make much sense and Copier's behavior is even inconsistent and unintuitive across the choice syntax options.

**Template**

Use the following `copier.yml` file:

```yaml
question_with_list_choices:
  choices:
    - a
    - a
    - b

question_with_dict_choices:
  choices:
    a: "A1"
    a: "A2"
    a: null
    b: null

question_with_tuple_choices:
  choices:
    - [a, "A1"]
    - [a, "A2"]
    - [a, null]
    - [b, null]
```

**To Reproduce**

```shell-session
$ copier $tpl $dst
🎤 question_with_list_choices (yaml)
 » a
   a
   b
🎤 question_with_dict_choices (yaml)
 » a
   b
🎤 question_with_tuple_choices (yaml)
 » a
   b
```

When selecting the default answer, the answers file has the following content:

```yaml
_commit: <commit hash>
_src_path: $tpl
question_with_dict_choices: a
question_with_list_choices: a
question_with_tuple_choices: a
```

**Expected behavior**
Copier should raise an error for duplicate choices. Also, as shown in the reproducible example, the current behavior is inconsistent, and for questions with dict or tuple choices it's even unclear which answer value is actually used.

**Screenshots/screencasts/logs**

**Environment**
 - OS: Ubuntu 20.04
 - Copier version: 0.0.0 (current `master`: 8ca78fa7696f2d8b718bcbc8641cfef67bbdd657)
 - Python version: 3.10.8
 - Installation method: local build

**Additional context**
n/a
