### ISSUE TITLE
Bootstrap a file/directory

### ISSUE THREAD

**Issue by pwwang** [copier-org/copier#1004]
**Is your feature request related to a problem? Please describe.**

I want to bootstrap a directory, based on a list of values. For example, consider the following structure:

```
project/
|- {{app}}/
   |- content.txt
```
I need to generate multiple `app/`-like directories when I have multiple "app"s.

**Describe the solution you'd like**

`copier.yml`
```yml
_bootstrappable:
  app: apps  
apps:
  type: list
  default:
    - todo
    - calendar
```

generates:

```
project/
|- todo/
   |- content.txt
|- calendar/
   |- content.txt
```

**Describe alternatives you've considered**

**Additional context**
