### ISSUE TITLE
feature: access `dst_path` in question context?

### ISSUE THREAD

**Issue by tlambert03** [copier-org/copier#1050]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to provide a default project name, based on the name of the destination path that the user provided on the cli

This looks a lot like the discussion in #20 ... but that was closed, and it's not entirely clear to me whether/how the intended goal was achieved.

**Describe the solution you'd like**
I'd like to be able to use something like this, to initialize a value based on the command line dest path arguments

```yaml
project_name:
  help: Name of your project
  default: "{{ dst_path | basename }}"
```

**Describe alternatives you've considered**

I've considered using the context hook extensions to hack at sys.argv

**Additional context**
