### ISSUE TITLE
Add support for validating JSON/YAML questions with JSON Schema

### ISSUE THREAD

**Issue by sisp** [copier-org/copier#1065]
**Is your feature request related to a problem? Please describe.**
Copier supports `type: json` and `type: yaml` questions which means their answers can be complex structured data. Copier also supports [answer validation via the `validator` field](https://copier.readthedocs.io/en/v7.0.1/configuring/#advanced-prompt-formatting) using a Jinja expression to render an error message or an empty string when validation succeeds. This validation approach is fine for simple answers but not well suited for complex structured data.

**Describe the solution you'd like**
JSON/YAML data can be validated very nicely using the widely adopted [JSON Schema](https://json-schema.org/) language. I suggest to add support for validating `type: json` and `type: yaml` questions using a JSON Schema document in addition to the Jinja based validation approach. The existing `validator` field could be reused to also accept a YAML object which contains the JSON Schema document. And the popular Python library [`jsonschema`](https://github.com/python-jsonschema/jsonschema) could be used to perform the validation of the data against the schema.

For example:

```yaml
complex_question:
  type: yaml  # or `json`
  validator:
    # Here comes the JSON Schema document that
    # validates a simple object in this example
    type: object
    required:
      - name
      - age
    additionalProperties: false
    properties:
      name:
        type: string
      age:
        type: integer
        minimum: 0
```

**Describe alternatives you've considered**
The existing validator approach using complex Jinja if-else rules could be used, but it would be very verbose and difficult to read.

**Additional context**
n/a

**Comment by yajo** [comment]
It seems to me like this could exist as a jinja extension. Something like this:

```yaml
_jinja_extensions:
  - something.jsonschema

complex_question:
  type: yaml  # or `json`
  validator: |-
    {% if complex_question is not jsonschema('./file.json') %}
      Nope. Chuck Testa.
    {% endif %}
```

That would give the feature a much broader utility. WDYT?

**Comment by sisp** [comment]
Good idea! 👍

I think it would be useful to give access to the JSON Schema validation result, so that it's possible to include some relevant information in the error message. For instance using Jinja's [`with` statement](https://jinja.palletsprojects.com/en/3.1.x/templates/#with-statement):

```yaml
complex_question:
  type: yaml  # or `json`
  validator: |-
    {% with error = jsonschema.validate(complex_question, './schema.json') %}
    {% if error %}Error: {{ error.message }}{% endif %}
    {% endwith %}
```

In this example, `error` would be an instance of [`ValidationError`](https://python-jsonschema.readthedocs.io/en/stable/api/jsonschema/exceptions/#jsonschema.exceptions.ValidationError).

We could make `jsonschema` globally accessible in the Jinja context when it is installed as a dependency or only when it is somehow enabled as a Jinja extension (I'd need to check how that works).
