### ISSUE TITLE
Validate answer when forcing update

### ISSUE THREAD

**Issue by drewoldag** [copier-org/copier#1073]
**Is your feature request related to a problem? Please describe.**
When my template includes questions with specific `choices`, there is no validation of the choice when I run copier update. 
For instance in my .copier.yaml file I have
```
preferred_linter:
    help: What tooling would you like to use to enforce code style?
    type: str
    default: pylint
    choices:
        pylint: pylint
        black: black
        none: none
```

If I run the following update after creating the new project: `copier --force --data preferred_linter="turtles" update`, there will be no validation that the updated answer corresponds to one of the original choices. Subsequently, "turtles" is recorded in the `.copier-answer.yml` file, and the assorted jinji logic that was expecting one of ("pylint", "black", or "none") get's really confused :) 

**Describe the solution you'd like**
Validate new answers entered via the CLI against the available .copier.yml file `choices`, `types`, `validator`, etc...

**Describe alternatives you've considered**
Other alternatives are to not use the `--data` CLI option. But this of course requires the user to go through all the questions again.

**Additional context**
Let me know if additional context is required.
