### ISSUE TITLE
'when: false' defaults not set in version 8

### ISSUE THREAD

**Issue by lhupfeldt** [copier-org/copier#1175]
### Describe the problem

Attributes set with `when: false` are empty in V8.
My templates use this extensively, so they are completely broken with V8.

### Template

copier.yaml:
```
 _min_copier_version: 8.0.0

project_name:
  type: str

full_package_name:
  type: str
  default: vvv
  when: false
```

Template:
```
project_name: {{ project_name }}
full_package_name: {{ full_package_name }}
```

Command:

### To Reproduce

Put files in `copier_error`

Run:
`copier copy -d project_name=uuu copier_error/ /tmp/ttt`

### Expected behavior

`{{ full_package_name }}`  is replaced with `vvv`

### Operating system

Linux

### Operating system distribution and version

Fedora release 38 (Thirty Eight)

### Copier version

copier 8.0.0

### Python version

Python 3.11.3

### Installation method

pip+pypi
