### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte on Windows

### ISSUE THREAD

**Issue by micmarty-deepsense** [copier-org/copier#1186]
### Describe the problem

`copier` does not work on Windows if a `copier.yml` is in UTF-8 encoding - it must be manually converted to Windows 1252. 

### Template

template doesn't matter, it can be:
```
# questions
project_name:
    type: str
    help: What is your project name?

module_name:
    type: str
    help: What is your Python module name?
```

### To Reproduce

1. Save your `copier.yml` in UTF-8 encoding
2. Run `copier copy <source-dir> <target-dir>`
3. You'll get this error
![charmap](https://github.com/copier-org/copier/assets/64484917/d1dfe9bd-ce79-46e9-b693-4dcdabed1373)

### Expected behavior

It should support unicode out of the box.

### Screenshots/screencasts/logs

Solution is to change the encoding to Windows 1252:
![image](https://github.com/copier-org/copier/assets/64484917/2568ef0c-6e92-4a54-a0eb-ab4c375d53a5)

### Operating system

Windows

### Operating system distribution and version

10

### Copier version

copier 8.0.0

### Python version

CPython 3.11

### Installation method

pip+pypi
