### ISSUE TITLE
Created new file after copier update seems to be deleted

### ISSUE THREAD

**Issue by nchal** [copier-org/copier#1202]
### Describe the problem

After doing a copier update, I cannot commit the incoming changes because the files seems to be deleted

### Template

```
# Configuration
# ----------------------
_envops:
  lstrip_blocks: false
  trim_blocks: false
  keep_trailing_newline: true

_exclude:
  - ".git/**"
  - ".releaserc.yml"
  - "copier.yml"
  - "tests"
  - "tests/**"

_skip_if_exists:
  - "cleyrop/*"

# Questions
# ----------------------
project_name:
  type: str
  help: What is the project name?

initial_codeowners:
  type: str
  help: Who are the codeowners use @gitlab_usernames space limited. If unsure, just use your @gitlab username, including the @ sign.

certmanager_issuer:
  type: str
  choices:
    - letsencrypt
    - customCA

external_oauth:
  type: bool
  default: false
  choices:
    - true
    - false

```

### To Reproduce

`copier --vcs-ref=ci/test_remove_copier_task update`

### Logs

```console
Copying from template version 4.0.0b15.post1.dev0+4e97db3
 identical  .
 identical  .gitleaks.toml
 identical  cleyrop
 identical  cleyrop/README.md
 identical  .tool-versions
 identical  .pre-commit-config.yaml
 identical  .checkov.yaml
 identical  scripts
 identical  scripts/prepare-dev-env.sh
 identical  scripts/update-asdf-version-variables.sh
 identical  scripts/install-asdf-plugins.sh
  conflict  .copier-version
 Overwrite .copier-version? [Y/n]
 identical  .git
 identical  docs
    create  docs/How_to_deal_with_Altas_as_hemera_developer.md
    create  docs/Global_Architecture_Overview.md
    create  docs/How_to_use_skeleton_as_hemera_developer.md
 identical  docs/resources
 identical  docs/resources/global_architecture_overview.drawio.png
    create  docs/resources/global_architecture_overview.drawio
 identical  docs/resources/change_cleyrop_chart_version_in_hemera_developers_env.png
 identical  docs/resources/retrieve_chart_version_in_job.png
 identical  docs/resources/charts_MR_change_values.png
 identical  LICENSE
  conflict  .copier-answers.yml
 overwrite  .copier-answers.yml
 identical  ingress-nginx
 identical  ingress-nginx/values.yaml.gotmpl
  conflict  helmfile.yaml
 Overwrite helmfile.yaml? [Y/n]
 identical  loki
    create  loki/develop.yaml.gotmpl
    create  loki/main.yaml.gotmpl
  conflict  loki/values.yaml.gotmpl
 Overwrite loki/values.yaml.gotmpl? [Y/n]
    create  loki/staging.yaml.gotmpl
 identical  README.md
 identical  .gitlab-ci-asdf-versions.yml
 identical  promtail
 identical  promtail/values.yaml.gotmpl
 identical  .yamllint.yaml
 identical  .editorconfig
 identical  prometheus
 identical  prometheus/values.yaml.gotmpl
 identical  .gitlab-ci.yml
 identical  .gitlab
    create  .gitlab/merge_request_templates
    create  .gitlab/merge_request_templates/MEP_Cleyrop.md
 identical  .gitlab/renovate.json
 identical  CODEOWNERS
 identical  CONTRIBUTING.md
 identical  external-dns
 identical  external-dns/values.yaml.gotmpl
  conflict  .gitignore
 Overwrite .gitignore? [Y/n]
```

### Expected behavior

Created files are in my filesystem  
BUT
the git status show me this
```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   .copier-answers.yml
        modified:   .copier-version
```

### Operating system

Linux

### Operating system distribution and version

Ubuntu 20.04

### Copier version

copier 7.0.1

### Python version

Python 3.8.10

### Installation method

pipx+pypi
