### ISSUE TITLE
Support hiding choices in a question

### ISSUE THREAD

**Issue by GytisBraz** [copier-org/copier#1212]
### Actual Situation

I have a question with multiple choices which depend on a previous question and I would like to be able to hide some of the choices from the user. Consider this example `copier.yaml` file:

```yaml
version:
  type: str
  help: Choose your Python version
  choices:
    - "3.8"
    - "3.9"

image:
  type: str
  help: Choose a base Docker image
  choices:
    slim (python==3.8):
      value: slim-3.8
      validator: '{% if version == "3.8" %}{% else %}does not apply{% endif %}'
    bullseye (python==3.8):
      value: bullseye-3.8
      validator: '{% if version == "3.8" %}{% else %}does not apply{% endif %}'
    slim (python==3.9):
      value: slim-3.9
      validator: '{% if version == "3.9" %}{% else %}does not apply{% endif %}'
    bullseye (python==3.9):
      value: bullseye-3.9
      validator: '{% if version == "3.9" %}{% else %}does not apply{% endif %}'
```

The user chooses a version, and depending on the version chosen, only some of the choices in the next answer will be 'selectable'. However, the 'unselectable' or 'disabled' choices in the second question are still visible to the user. In this toy example they are very similar to the 'enabled' choices and add clutter.
![Screenshot 2023-06-22 at 14 18 16](https://github.com/copier-org/copier/assets/106960916/fcbc6501-29a1-4a90-9f4a-2d5ff35b2799)

The situation isn't too bad with just a few different versions and images but you can imagine things would get very cluttered with more options.

### Desired Situation

It would be nice to be able to have less clutter in the CLI prompt. Ideally, some way to be able to only show some choices, and hide others.

### Proposed solution

One idea is to have another parameter, in addition to the `validator` and `value` parameters in the dict-style choices. Perhaps a parameter such as `hidden` which could be set to `true` and would then result in the choice being hidden from the user. E.g. something like

```yaml
question:
  type: str
  help: Some help text
  choices:
    first:
      value: some-value
      validator: ...
      hidden: true # could be dynamically set
    ...
```

Or perhaps a question-level parameter, e.g. `hide_disabled`, which could hide the choices which don't pass the validator. E.g.

```yaml
question:
  type: str
  help: Some help text
  hide_disabled: true
  choices:
    ...
```

**Comment by sisp** [comment]
Thanks for your feature request, the detailed description and solution proposal. :pray:

Copier uses [`questionary`](https://github.com/tmbo/questionary) for prompting. Questions with choices are mapped to `questionary`'s [`select`](https://github.com/tmbo/questionary/blob/eebbc4953e627bb69d854ebb409024e345b186d1/questionary/prompts/select.py) question type which, and questions are marked as disabled by setting [`Choice(..., disabled="<message>")`](https://github.com/tmbo/questionary/blob/eebbc4953e627bb69d854ebb409024e345b186d1/questionary/prompts/common.py#L64).

I see two options to hide disabled questions:

1. Request this feature upstream in `questionary`. Once available, Copier could use it.
2. When a choice or question is configured to hide a disabled choice, we could insert something like

    ```python
    if value.get("hidden", False):
        continue
    ```

    after

    https://github.com/copier-org/copier/blob/5a5e445f0cff7356436af1d51031c3b3d8d0114d/copier/user_data.py#L328

    If we introduce a question-level setting, we can internally propagate it down to each choice, so that hiding choices can always be handled there.

WDYT, @copier-org/maintainers?

**Comment by yajo** [comment]
Let me offer you a couple of solutions that currently work, just to see if you stillfeel the need for this feature after trying those. 

The 1st one, obvious from the questionary you provided, is to just ask for the base distro:

```yaml
version:
  type: str
  help: Choose your Python version
  choices:
    - "3.8"
    - "3.9"

image:
  type: str
  help: Choose a base Docker image
  choices:
    - slim 
    - bullseye
```

You can do `{{image}}-{{version}}` to get the final result.

The second solution would be to see if it makes sense to split the selections in two questions. Each one of them can have a `when` clause, so you show one selection list or the other. Later in the template, you'd have to do a small gimnastic to get the value: `{{ selection_1|d(selection_2)}}` or similar.
