### ISSUE TITLE
_copier_conf.dst_path not filled correctly during `copier update`

### ISSUE THREAD

**Issue by francesco086** [copier-org/copier#1285]
### Describe the problem

I have a copier template project that makes use of `_copier_conf.dst_path`.

When I run `copier copy ...`, then the variable is set to the relative path I specify as dst, for example `docker` (folder).

When I run `copier update ...`, then the variable is set to what seems to be the absolute path to the temporary directory used during the update, for example `/var/folders/zw/nb7v8mxs10j2_0rw8w4l8txr0000gn/T/copier.main.new_copy.g7jykqzk/docker`.

This leads to an unwished change in the templates that make use of this variable.

### Template

This is a template where I use `_copier_conf.dst_path`. It's a `.gitlab-ci.yml`.

```yml
include:
- template: Security/Container-Scanning.gitlab-ci.yml

build_test_docker_image:
  stage: build
  extends: .docker_auth
  image: ${DOCKER_REGISTRY}/docker:latest
  script:
    - docker image build -t {{ docker_image_name }} {{ _copier_conf.dst_path }}
    - sh {{ _copier_conf.dst_path }}/helper-scripts/deploy-test-image.sh

test_built_docker_image:
  stage: test
  image: ${DOCKER_REGISTRY}/{{ docker_image_name }}:test-${CI_PIPELINE_ID}
  script:
    - chmod +x {{ _copier_conf.dst_path }}/test.sh
    - ./{{ _copier_conf.dst_path }}/test.sh

determine_docker_image_tags:
  stage: deploy
  image: ${DOCKER_REGISTRY}/{{ docker_image_name }}:test-${CI_PIPELINE_ID}
  script:
    - chmod +x {{ _copier_conf.dst_path }}/determine-docker-image-tags.sh
    - DOCKER_IMAGE_TAGS="$(./{{ _copier_conf.dst_path }}/determine-docker-image-tags.sh)"
    - echo "Docker image will be tagged with the following tags (space separated) '${DOCKER_IMAGE_TAGS}'"
    - echo "DOCKER_IMAGE_TAGS=${DOCKER_IMAGE_TAGS}" >> docker-image-tags.env
    - echo "DOCKER_IMAGE_TAG_TO_SCAN=$(echo ${DOCKER_IMAGE_TAGS} | cut -d ' ' -f 1)" >> docker-image-tags.env
  artifacts:
    reports:
      dotenv: docker-image-tags.env

deploy_docker_image:
  stage: deploy
  needs:
    - job: determine_docker_image_tags
      artifacts: true
  extends: .docker_auth
  image: ${DOCKER_REGISTRY}/docker:latest
  script:
    - sh {{ _copier_conf.dst_path }}/helper-scripts/deploy-prod-image.sh "${DOCKER_IMAGE_TAGS}"
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

container_scanning:
  stage: deploy
  needs:
    - job: determine_docker_image_tags
      artifacts: true
    - job: deploy_docker_image
  dependencies:
    - determine_docker_image_tags
  variables:
    CS_IMAGE: ${DOCKER_REGISTRY}/{{ docker_image_name }}:${DOCKER_IMAGE_TAG_TO_SCAN}
    CS_REGISTRY_USER: ${DOCKER_REGISTRY_USER}
    CS_REGISTRY_PASSWORD: ${DOCKER_REGISTRY_PASSWORD}
  before_script:
    - >
        echo "Next step is to scan the docker image ${DOCKER_REGISTRY}/{{ docker_image_name }}:${DOCKER_IMAGE_TAG_TO_SCAN}"
  rules:
  - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

.docker_auth:
  before_script:
    - mkdir -p ${HOME}/.docker
    - echo ${DOCKER_AUTH_CONFIG} >> ${HOME}/.docker/config.json
```

### To Reproduce

1. Enter in an empty directory
2. `git init`
3. `copier copy --vcs-ref '1.0.0' 'https://github.com/francesco086/copier-issue.git' 'docker'` (answer e.g. "foo" to the question)
4. `git add docker && git commit -m "use v1.0.0"`
5. `copier update --defaults --trust --vcs-ref '1.1.0' 'docker'`
6. Observe the changes in `docker/.gitlab-ci.yml`

### Expected behavior

I would expect `_copier_conf.dst_path` to take the same value during `copy` and `update`

### Operating system

macOS

### Operating system distribution and version

13.4.1

### Copier version

copier 8.1.0

### Python version

Python 3.11.4

### Installation method

pip+pypi

### Additional context

Template repo for reproducing the problem: https://github.com/francesco086/copier-issue

**Comment by francesco086** [comment]
Hi @sisp !

Regarding the first comment, of course I am well aware of it, it is described in the README, right after "If path/to/destination is other than .", with also an example.

Hope this can be solved, I think it is very useful to have available in the templates the destination path passed by the user to the cli command. The workaround for us otherwise would be to ask it again to the user in the questions.

**Comment by sisp** [comment]
Ah, sorry, @francesco086, I hadn't noticed that section your README and the rationale for using the destination path in this way. I believe this is a valid use case.

The only fix I can think of off the top of my head is through a post-processing step in the update algorithm. I'll look into it tomorrow and get back to you.

**Comment by sisp** [comment]
I've given this more thought and experimented with some potential fix against a test case that indeed reproduces your problem, @francesco086. But I've concluded that I don't see how this could be fixed, and I'm back to thinking your usage of `_copier_conf.dst_path` isn't a good idea here. Let me elaborate.

1. Rendering `_copier_conf.dst_path` in files (essentially anywhere except in [`_message_{before,after}_copy`](https://copier.readthedocs.io/en/latest/configuring/#message_before_copy), [tasks](https://copier.readthedocs.io/en/latest/configuring/#tasks), and [migrations](https://copier.readthedocs.io/en/latest/configuring/#migrations)) tends to be a bad idea because the path is rendered in an OS-specific way, i.e. as a POSIX path on Linux/macOS and as a Windows path on Windows. In your case, I presume the CI jobs run in Linux containers, so you'd actually need to make sure that `_copier_conf.dst_path` gets rendered as a POSIX path even when a project creator uses Windows: `{{ _copier_conf.dst_path.as_posix() }}` 

1. Copier doesn't require the destination path to be a relative path. In your case, a project creator could use an absolute path which resolves to the same location as the original relative path:

    ```diff
    -copier copy <src> path/to/destination
    +copier copy <src> $PWD/path/to/destination
    ```

    But the generated project wouldn't work with an absolute path in your case. Copier, however, would be perfectly fine with either destination path. So, you're requiring a user to use a relative destination path by means of documentation &ndash; this may work, but there's no technical guarantee.

1. The post-processing idea I had won't work:

     * As mentioned before, the `_copier_conf.dst_path` path is rendered in an OS-specific way. If we simply replaced all occurrences of the temporary path by the user-provided destination path, we'd need to consider both POSIX and Windows paths to be sure we're replacing all those occurrences.
     * But template creators could apply a Jinja filter such as `lower()` to `_copier_conf.dst_path`, e.g. `{{ _copier_conf.dst_path.as_posix() | lower }}`, so if the path contained upper-case characters, we'd miss those occurrences because of case mismatch. And that's just a basic filter, we can't anticipate what crazy transformations template creators might want to apply to this path.

1. Somehow setting the destination path _only in the render context_ to the user-provided path won't work either because the render context is also passed to [tasks](https://copier.readthedocs.io/en/latest/configuring/#tasks) and [migrations](https://copier.readthedocs.io/en/latest/configuring/#migrations) which might require the "true" destination path (i.e. the one where update algorithm generates temporary projects based on the old and new version of the template). Then, you might think we could only set the user-provided destination path only in the render context for rendering files, but who knows what template creators are doing in tasks and migrations, perhaps they need the "true" destination path there as well because they are creating some file programmatically that shall contain this path. It's impossible to anticipate.

1. We could think of having two context variables: `_copier_conf.dst_path` and (for the lack of a better name now) `_copier_conf.user_dst_path` where the latter is the path you pass to Copier's CLI. That could work, but it somehow leaks internals of Copier's update algorithm which might change in the future.

To be honest, I think adding a question that asks for a subdirectory path isn't too bad in your case. It's more explicit than using the destination path and you could enforce the answer to be a relative path through validation. But I believe we should improve the documentation on the implications of using `_copier_conf.dst_path`.

**Comment by francesco086** [comment]
Hi @sisp many thanks for the detailed answer and the effort!

I don't know the copier source code, but I immediately thought of the option 5 you mentioned. To me as a user, the arguments provided to the CLI should be available as-provided, like any other question to the answers. However, you have clearly more insights than me, so if you say that it's not a good way, then you are probably right.

Thanks for the relative-vs-absolute path as user dst argument, didn't think of that.

So, I think we will follow your suggestion and add one extra question. Do you think that there is a way to at least hint, as a default answer, the path provided as dst to the CLI?

**Comment by sisp** [comment]
> I don't know the copier source code, but I immediately thought of the option 5 you mentioned. To me as a user, the arguments provided to the CLI should be available as-provided, like any other question to the answers. However, you have clearly more insights than me, so if you say that it's not a good way, then you are probably right.

Let's say I'm not sure whether this is a good way, but I understand your expectation about the path value of `_copier_conf.dst_path`. I think it would help to get opinions from the other @copier-org/maintainers. :pray:

> So, I think we will follow your suggestion and add one extra question. Do you think that there is a way to at least hint, as a default answer, the path provided as dst to the CLI?

With #1050 implemented, this might be possible, e.g.:

```yaml
subdir:
  type: str
  default: >-
    {%- if not _copier_conf.dst_path.is_absolute() -%}
    {{ _copier_conf.dst_path.as_posix() }}
    {%- endif -%}
```
