### ISSUE TITLE
Variable not rendered in `message_after_copy`

### ISSUE THREAD

**Issue by bartvanb** [copier-org/copier#1347]
### Describe the problem

I am creating a copier template with a `_message_after_copy` that contains an `algorithm_name` variable, but it is not rendered.

This part of my copier.yaml:

```
_message_after_copy: |
  Your algorithm template "{{ algorith_name }}" has been created successfully!
```

While providing a value for `algorithm_name`, it is not printed at the end of `copier copy`:
```
Your algorithm template "" has been created successfully!
```

Other details:
- `algorithm_name` is present as expected in `.copier-answers.yml`
- I followed the instructions in [this part of the docs](https://copier.readthedocs.io/en/stable/configuring/#message_after_copy)

### Template

```
algorithm_name:
    type: str
    help: What is your algorithm name?

_message_after_copy: |
  Your algorithm template "{{ algorith_name }}" has been created successfully!
```

### To Reproduce

1. `conda create -n test-copier python=3.10`
2. `conda activate test-copier`
3. `pip install copier`
4. inside the directory with the copier template, run `copier copy . ../test`
5. Fill out a value for the algorithm name
6. Observe issue that algorithm name is not printed

### Expected behavior

Expect `some_input_name` at the end as in:
```
Your algorithm template "some_input_name" has been created successfully!
```

### Operating system

Windows

### Operating system distribution and version

Windows 10 Enterprise

### Copier version

8.3.0

### Python version

3.10.13

### Installation method

pip+pypi
