### ISSUE TITLE
Using --data with a multiselect based choice

### ISSUE THREAD

**Issue by chrisdaish** [copier-org/copier#1474]
### Describe the problem

Follow on from: https://github.com/orgs/copier-org/discussions/1473

### Template

```
fruit:
    type: str
    help: "Fruit?"
    choices:
        - apple
        - pear
        - banana
    multiselect: true
```

### To Reproduce

```
$ copier copy --data 'fruit=apple' ../copier-issue .
...
ValueError: Invalid choice
```

### Expected behavior

Primary:
--data is able to find the 'apple' from the 'fruit' multiselect based choice, and select it.

Secondary:
To support multiple options perhaps multiple --data entries are required akin to:

```
--data 'fruit=apple' --data 'fruit=banana'
```

or comma separated

```
--data 'fruit=apple, banana'
```

or an array?

```
--data 'fruit=[apple, banana]'
```

### Operating system

macOS

### Operating system distribution and version

Sonoma 14.2.1

### Copier version

copier 9.1.0

### Python version

Python 3.9.6

### Installation method

pip+pypi
