### ISSUE TITLE
Migration with alpha, beta etc. support

### ISSUE THREAD

**Issue by henningWoehr** [copier-org/copier#1487]
### Actual Situation

Currently, when we want to test a version before finally releasing it, there is no nice way to use alpha, beta or release candidates, as the migration will not be triggered, since these versions are per PEP 440 below the final version. Currently we may use one of `1.2.3post.dev`, `1.2.3post` or `1.2.3+testing` (not decided yet).

### Desired Situation

In the copier yaml, under _migrations, there should be an option to include prereleases in the migration

### Proposed solution

```yaml
_migrations:
  - version: v0.7.0
    include_pre: true
    before:
      ...
```

```yaml
_migrations:
  - version: v0.7.0
    include_pre: alpha  # beta, rc
    before:
      ...
```

These two ways come to mind. The first simply says include all prereleases, the second defines the minimum prerelease type, since that is still comparable through PEP 440.

While writing this, I noticed that I can simply use `1.2.3rc` as the version for the migration, but since I find the solution a bit cleaner, I will still propose this feature
