### ISSUE TITLE
9.1.1 skip-exclude changes result in .copier-answers.yml not being created

### ISSUE THREAD

**Issue by lhern207** [copier-org/copier#1504]
### Describe the problem

A recent change included in version 9.1.1 results in the answer file not being created when running the `copier copy` command.

### Template

`copier.yaml` - Located in template root
```
_subdirectory: skeleton
_templates_suffix: ""
_exclude:
  - "*"
  - "!bitbucket-pipelines.yml"
  - "!.copier-answers.yml"

cookiecutter:
  type: json
  multiline: true
  default: { app_tag: "", region: "", app_business_owner: "", app_domain: "" }
```

`{{_copier_conf.answers_file}}` - Located in `/skeleton`
`{{ _copier_answers|to_nice_yaml -}}`

### To Reproduce

1. `pip3 install copier==9.1.0`
2.  Run `copier copy -f --data-file {DATA_FILE_LOCATION} --vcs-ref main {REMOTE_TEMPLATE_URL} {LOCAL_COMPONENT_PATH}`
3. See Output:
```
Copying from template version 0.0.0.post8.dev0+63430b0
 identical  .
  conflict  .copier-answers.yml
 overwrite  .copier-answers.yml
 identical  bitbucket-pipelines.yml
```

1. `pip3 install copier==9.1.1`
2.  Run `copier copy -f --data-file {DATA_FILE_LOCATION} --vcs-ref main {REMOTE_TEMPLATE_URL} {LOCAL_COMPONENT_PATH}`
3. See Output:
```
Copying from template version 0.0.0.post7.dev0+e57b3fd
 identical  .
 identical  bitbucket-pipelines.yml
```

### Expected behavior

2.  Run `copier copy -f --data-file {DATA_FILE_LOCATION} --vcs-ref main {REMOTE_TEMPLATE_URL} {LOCAL_COMPONENT_PATH}`
3. See Output:
```
Copying from template version 0.0.0.post8.dev0+63430b0
 identical  .
  conflict  .copier-answers.yml
 overwrite  .copier-answers.yml
 identical  bitbucket-pipelines.yml
```

### Operating system

macOS

### Operating system distribution and version

Sonoma 14.1.1

### Copier version

9.1.1

### Python version

3.9.2

### Installation method

pip+pypi
