### ISSUE TITLE
Answers Groups

### ISSUE THREAD

**Issue by guilhermeprokisch** [copier-org/copier#1536]
### Actual Situation

Currently, there is no option to categorize answers. The ability to group responses can be beneficial in organizing them logically and enhancing the functionality of another tools.

### Desired Situation

I'd appreciate having a feature in the copier-answers.yaml that enables grouping of answers. This would allow me to structure answers in a way similar to:

```yaml
_commit: 0.1.0-42-ga1b2c3d
_src_path: git@github.com:yourusername/your-repo.git

project:
  name: mock-project
  description: This is a mock project for testing

cloud_function:
  python_version: "3.12"
  trigger_type: pubsub
```

### Proposed solution

Adjust the code to incorporate a group option in each answer, and modify the _copier_answers output to a nested JSON format. Additionally, make the copy/update/others commands aware of this new format.

```yaml
name:
  type: str
  default: "{{ project_name_default }}"
  help: What is your project name?
  group: project

project_description:
  type: str
  help: What is your project description?
  group: project

trigger_type:
  type: str
  help: What is function trigger type?
  default: http
  choices:
    - http
    - pubsub
  group: cloud_function

python_version:
  type: str
  help: What is your project python version?
  choices:
    - 3.12
    - 3.11
  group: cloud_function 

```

The``_copier_answers`` output with groups

```json
{
   "_commit":"0.0.11-22",
   "_src_path":"git@github.com",
   "project":{
      "project_name":"some_name",
      "project_description":"some_desc"
   },
   "cloud_function":{
      "trigger_type":"http",
      "python_version":"3.12"
   }
}
```
