### ISSUE TITLE
default option for choices with multiselect

### ISSUE THREAD

**Issue by twsl** [copier-org/copier#1594]
### Describe the problem

When enabling multiselect, the default value is not selected

### Template

```yaml
python_version:
  type: str
  help: What version of python are you targeting?
  default: "3.11"
  choices:
    - "3.8"
    - "3.9"
    - "3.10"
    - "3.11"
    - "3.12"
 
github_runner_python_version:
  type: str
  help: Which Python versions do you want to use on your Github Runner?
  default: "{{ python_version }}"
  multiselect: true
  choices:
    - "3.8"
    - "3.9"
    - "3.10"
    - "3.11"
    - "3.12"
 ```

### To Reproduce

Use the supplied template and copy, see that the version is not selected

### Expected behavior

`github_runner_python_version` already has the `python_version` selected

### Operating system

Linux

### Operating system distribution and version

Debian bookworm

### Copier version

copier 9.2.0

### Python version

Python 3.11.8

### Installation method

pip+pypi

**Comment by sisp** [comment]
That's because answers (and, thus, also the default value_s_) to multi-select choices are represented by a _list_ of values:

```diff
 github_runner_python_version:
   type: str
   help: Which Python versions do you want to use on your Github Runner?
-  default: "{{ python_version }}"
+  default: ["{{ python_version }}"]
   multiselect: true
   choices:
     - "3.8"
     - "3.9"
     - "3.10"
     - "3.11"
     - "3.12"
```

**Comment by sisp** [comment]
I'm closing this issue because I believe your problem was only due to a misunderstanding. But feel free to add comments or reopen the issue if needed.

**Comment by twsl** [comment]
that is what i previously had, but that only works with hardcoded values like this:
```yaml
github_runner:
  type: str
  help: Which Python versions do you want to use on your Github Runner?
  default: [ubuntu-latest]
  multiselect: true
  choices:
    Ubuntu: ubuntu-latest
    Windows: windows-latest
    MacOS: macos-latest
```
