### ISSUE TITLE
Conditional questions

### ISSUE THREAD

**Issue by Yajo** [copier-org/copier#161]
I guess this issue depends on #90 and it would let us declare questions to be conditional:

```yaml
using_smtp:
  type: bool
  default: no

smtp_host:
  type: str
  when: '[[ using_smtp ]]'
```
