### ISSUE TITLE
Nested Questions Asked Incorrectly

### ISSUE THREAD

**Issue by davidbrownell** [copier-org/copier#1697]
### Describe the problem

I have a template with a choice of 2 values, where a different question should be asked based on the previous choice.

```
project_type:
  type: str
  choices:
    - One
    - Two

one_question:
  type: bool
  when: "{{ project_type == 'One' }}"
  default: False

two_question:
  type: bool
  when: "{{ project_type == 'Two' }}"
  default: False
```

In addition, an additional question should be asked if the response to one of the choice-specific questions was True:

```
one_nested:
  type: bool
  when: "{{ one_question }}"
  default: False

two_nested:
  type: bool
  when: "{{ two_question }}"
  default: False
```

Things work as expected when running `copier copy...` the first time around. However, when running `copier copy...` (on the same target directory) with a different choice, copier prompts for an answer to the original nested question in addition to the nested question associated with the new choice (this is clearer in the screenshots below).

### Template

https://github.com/davidbrownell/copier-TemplateIssue

### To Reproduce

1. Run `copier copy https://github.com/davidbrownell/copier-TemplateIssue <output_dir>`
2. Answer `project_type: One`, `one_question: Y`, `one_nested: Y`
3. Run `copier copy https://github.com/davidbrownell/copier-TemplateIssue <output_dir>`
4. Answer `project_type: Two`
5. Note that you are prompted to answer `one_nested` even though `one_question` has defaulted to False.

### Expected behavior

one-related questions should not be asked when the project_type is set to Two.

### Screenshots/screencasts/logs

![image](https://github.com/copier-org/copier/assets/6353056/1b9390c0-baf2-45e5-a9fd-c366ee8f8627)

### Operating system

Windows

### Operating system distribution and version

Windows 11

### Copier version

copier 9.3.1

### Python version

CPython 3.12

### Installation method

pip+pypi
