### ISSUE TITLE
Enhance Multiselect Questions with Choice Dependencies

### ISSUE THREAD

**Issue by farhaan-shamsee** [copier-org/copier#1700]
### Actual Situation

Currently, as I understand the choices in a multiselect questions are not dependent on each other. 

For example:
```yaml
features:
  help: Please select the features you would like to add.
  default: [feature_a]
  type: str
  multiselect: true
  choices:
    "Feature A (Description A)": "feature_a"
    "Feature B (Description B)": "feature_b"
    "Feature C (Description C)": "feature_c" #This needs feature A as prerequisite
    "Feature D (Description D)": "feature_d"
    "Feature E (Description E)": "feature_e"
    "Feature F (Description F)": "feature_f"
  when: "[2[ enable_features ]2]"
```

In the above case if the Feature C needs feature A as pre-requisite, I do not have a way to enforce it.

### Desired Situation

I would like to request a feature that allows choices within the same question can be made dependent on each other. This would help in scenarios where selecting one option should be mandatory for selecting another.

Like in our above example, if the user tries to select "Feature C" without selecting "Feature A", they should see an error message or prompt.

This feature would enhance the flexibility and usability by allowing more complex dependencies between choices.

Currently, I enforce it using the validator for the whole question which has a script which just checks if `feature_c in enable_feature and feature_a not in enable_features`  then give error.
