### ISSUE TITLE
Conditional argument ignored when updating

### ISSUE THREAD

**Issue by lhupfeldt** [copier-org/copier#1727]
### Describe the problem

Commandline data argument is ignored when commandline value is changed during update.
Argument is not remembered in answers file.

### Template

[copier_ignored_arg_bug.zip](https://github.com/user-attachments/files/16560894/copier_ignored_arg_bug.zip)

### To Reproduce

Create a copier.yaml with an argument which is conditional based on another argument.
```
_min_copier_version: 9.0.0

_subdirectory: "template"

_exclude:
  - "*~"

_message_before_copy: |
  Hi

project_name:
  type: str
  default: X

# Hidden options used for testing

show_internal_test_options:
  type: bool
  help: "Show options for internal use for testing template."
  default: false
  when: false

with_internal1:
  type: bool
  help: "Internal opt 1"
  default: false
  when: "{{ show_internal_test_options }}"
```
Git commit template.
Expand template with "hidden" data arg specified on commandline.
```
 ]$ mkdir ttt && cd ttt && copier copy ../copier_ignored_arg_bug . --defaults --data with_internal1=true 
```
Value of `with_internal1` is correctly expanded as `True` in template file, but is *not* store in answers file.
Commit subproject.
Make a change in template, e.g. the message. Commit.
Update subproject with new value of `with_internal1`
```
 ttt]$ copier update -A --data with_internal1=false
```
Value of `with_internal1` is unchanged and remains expanded as `True` in template file! The template file is unchanged, only answers file is update (with new git commit).

### Expected behavior

The template file should be updated with the value specified on commandline.
Copier should save the value in the answers file.

### Operating system

Linux

### Operating system distribution and version

Fedora

### Copier version

9.3.1

### Python version

3.11.8

### Installation method

pip+pypi
