### ISSUE TITLE
Custom _answers_file value is not taken into account for update and recopy 

### ISSUE THREAD

**Issue by the-other-dev** [copier-org/copier#1740]
### Describe the problem

When I specify a custom name for the answers file via `_answers_file`, then the `copy` command creates the file as expected.

In the template, there is a `{{ _copier_conf.answers_file }}.jinja` with the content:

```
# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
{{ _copier_answers|to_nice_yaml -}}
```

The `copier.yml` contains the option `_answers_file: .bootstrap.yml`.

When using the `recopy` command, then the error message is "Cannot recopy because cannot obtain old template references from `.copier-answers.yml`."

When I change the filename from `.bootstrap.yml` to `copier-answers.yml`, then the recopy works as expected.

When using the `update` command, then the error message is "TypeError: Template not found". Changing the filename again  to `copier-answers.yml`, makes the command work as expected.

If relevant, I also use `--data-file` to provide an answers file.

### Template

I think the template is not relevant in this case.

The `input.yml` content looks like this:

```yaml
customer_name: foo-bar-customer
customer_image_version: 1.2.3
environments:
  - dev
  - prod
```

The `copier.yml` content looks like this:

```yaml
---
_subdirectory: template

_answers_file: .bootstrap.yml

# Parameters / copier questions
customer_name:
  type: str
  help: What is the name of the customer?

customer_name_slug:
  type: str
  help: A slug of the customer name (lower-case + kebap case)
  default: "{% from 'slugify.jinja' import slugify %}{{ slugify(customer_name) }}"

customer_image_version:
  type: str
  help: What is the version of the customer image?

environments:
  type: str
  help: Which environments does the customer use?
  default: ""
  multiselect: true
  choices:
    - "dev"
    - "iat"
    - "prod"
```

### To Reproduce

Update command: `copier update --vcs-ref main --data-file input.yml --defaults my-custom-repo`

Recopy command: `copier recopy --vcs-ref main --data-file input.yml --defaults my-custom-repo`

### Expected behavior

Based on the configured `_answers_file`, it should read the correct answers file in the repository.

### Operating system

macOS

### Operating system distribution and version

14.6.1

### Copier version

copier 9.3.1

### Python version

Python 3.12.5

### Installation method

pipx+pypi
