### ISSUE TITLE
Add a variables section to the copier.yaml file

### ISSUE THREAD

**Issue by OhioDschungel6** [copier-org/copier#1807]
### Actual Situation

Sometimes it is useful to have a key available globally for all templates which is no user input.
Examples:
- I want to have a version available as key everywhere, because if i update it i don't want to update it in 10 locations but only in one.
- I want to use an answer with more complex filters used in many places and i don't want to reapply the filters in every file.

Atm this can be done with a workaround:
```yaml
version:
  type: str
  default: "1.0.0"
  when: false

module_name_camelcase: #module_name is a key which was defined earlier as question.
  type: str
  default: "{{ module_name.split('_') | map('capitalize') | join('') }}"
  when: false
```

While using `when: false` is a fix for the problem. It kinda mixes questions and variables and also uses confusing syntax.

### Desired Situation

Add a new section to the copier.yml file: which allows defining variables and constants.
E.g.
```yaml
_variables:
  - version: "0.2.0"
  - module_name_camel: "{{ module_name.split('_') | map('capitalize') | join('') }}"
```
