### ISSUE TITLE
copier copy didn't copy my uncommit file even though I added -r HEAD option

### ISSUE THREAD

**Issue by kamontat** [copier-org/copier#1887]
### Describe the problem

copy on repository contains uncommit files doesn't works even when added `-r HEAD` option.

### Template

hello {{name}}

### To Reproduce

1. Create empty directory
2. Create **copier.yaml** contains content below

```yaml
_min_copier_version: 9.4.1
_subdirectory: templates
name:
  type: str
  help: What is your name?
```

3. Create **templates** directory and file named **message.txt**
4. The file should contains `hello {{name}}`

```yaml
$PWD/example:
  copier.yaml: |
    _min_copier_version: 9.4.1
    _subdirectory: templates
    name:
      type: str
      help: What is your name?
  templates/message.txt: |
    hello {{name}}
```

5. Run `copier copy . .temp` and it should works normally
6. Run `git init`
7. Rerun `copier copy . .temp` again and it doesn't works anymore
8. Even with `copier copy -r HEAD . .temp`, it doesn't works as well

![CleanShot 2024-12-12 at 17 50 31@2x](https://github.com/user-attachments/assets/45743133-a4c4-42a9-90bc-4010fd41b8ae)

### Logs

```console
.../copier/9.4.1/venv/lib/python3.12/site-packages/copier/vcs.py:209: DirtyLocalWarning: Dirty template changes included automatically.
  warn(

Copying from template version 0.0.0.post1.dev0+9e08b53
```

### Expected behavior

it copy templates to target directory.

### Operating system

macOS

### Operating system distribution and version

MacOS 15.1.1

### Copier version

copier 9.4.1

### Python version

Python 3.12.2

### Installation method

pip+pypi
