### ISSUE TITLE
Dynamic choices

### ISSUE THREAD

**Issue by jazzyray** [copier-org/copier#2025]
### Describe the problem

Hello,

I am trying to use a dynamic choices following the example copier.yml on the [documentation site](https://copier.readthedocs.io/en/stable/configuring/#advanced-prompt-formatting)

```yaml
language:
    type: str
    help: Which programming language do you use?
    choices:
        - python
        - node

dependency_manager:
    type: str
    help: Which dependency manager do you use?
    choices: |
        {%- if language == "python" %}
        - poetry
        - pipenv
        {%- else %}
        - npm
        - yarn
        {%- endif %}
```

However, the choices output does not render the template..(see screen shot)

### Template

```yaml
language:
    type: str
    help: Which programming language do you use?
    choices:
        - python
        - node

dependency_manager:
    type: str
    help: Which dependency manager do you use?
    choices: |
        {%- if language == "python" %}
        - poetry
        - pipenv
        {%- else %}
        - npm
        - yarn
        {%- endif %}
```

### Logs

```console

```

### Expected behavior

I would expect a the template string to render two options...

### Screenshots/screencasts/logs

<img width="501" alt="Image" src="https://github.com/user-attachments/assets/ed2f0459-1008-493f-b097-9665189a11eb" />

### Operating system

Linux

### Operating system distribution and version

ubuntu 

### Copier version

9.6.0

### Python version

3.11

### Installation method

pipx+pypi
