### ISSUE TITLE
Copier update inside a project using _subdirectory duplicates project structure

### ISSUE THREAD

**Issue by ferreteleco** [copier-org/copier#2076]
### Describe the problem

When I create a project from a template inside a _subdirectory, the copy process runs seamlessly and generate a project structure like the following:

```
AWPRO-awesome_repo/
  .git
  .copier-answers.yml
  awpro_awesome_repo/
    file.py
    file_2.py
```

As expected.

The problem is that, whenever I want to update the project, the templated variables aren't updated and a new folder is created inside my project's directory:

```
AWPRO-awesome_repo/
  .git
  .copier-answers.yml
  awpro_awesome_repo/
    file.py
    file_2.py
  AWPRO-awesome_repo/
    .copier-answers.yml
    awpro_awesome_repo/
      file.py
      file_2.py
```

Note that instead of updating the project, it creates the project again as a nested folder inside the current project, behavior which I believe is unintended.

### Template

I have a template structure like the following:

```
template/
  {{ repo_name }}/
    {{ module_name }}/
        file.py
        file_2.py
    .copier-answers.yml
copier.yml
```

With the use of `_subdirectory: template` correctly specified in the copier.yml file.

```yml
# copier.yml

project_name:
  type: str
  help: What is the project name?
  placeholder: AWPRO-awesome_repo
  validator: >-
    {% if not project_name %}
      "project_name" cannot be empty.
    {% endif %}

module_name:
  type: str
  help: What is the name of the package to develop?
  default: |-
    {{ project_name.lower().replace(' ', '_').replace('-', '_') }}
  validator: >-
    {% if not (module_name.split(" ") | length == 1 ) %}
    "module_name" must be a unique word (no spaces).
    {% endif %}

_subdirectory: template
```

### To Reproduce

1. Run `copier copy <TEMPLATE_URL> .`
2. Move inside of the project , initialize git and commit the changes (project's initial state).
3. Run: `copier update --defaults --data  module_name=new_module_name`
4. Look inside AWPRO-awesome_repo and find another directory called AWPRO-awesome_repo/new_module_name

### Logs

```console

```

### Expected behavior

I was expecting the project to be updated correctly without creating any subdirectory inside. I saw in #1120 that OP "fixed it" by removing the {{ project_name }} step, but for my use case* it would be lovely if that templating could be maintained.

I'd appreciate a fix / explanation on how could I obtain a similar behavior.

*Such use case is, for example:
- Being able to create a base project structure with a project name that is both the name of the top-level directory and also is used inside source files along the project.
  - Responses file should live inside it in order to be commited to the project's repository and be tracked.
- Being able to add a subdirectory inside that bas project, for example a .devcontainer folder (using a specific template) with:
  - The responses file living inside it.
  - Can be added from project's root as `copier copy <DEVCONTAINER_TEMPLATE_URL> .`.

### Operating system

Windows

### Operating system distribution and version

Windows 11

### Copier version

9.6.0

### Python version

3.12.2

### Installation method

pip+git
