### ISSUE TITLE
Add for-loop choice generation to mkdocs documentation

### ISSUE THREAD

**Issue by wolfiex** [copier-org/copier#2078]
### Actual Situation

The ability to dynamically create choices is really useful and it should be given as an example in the documentation. 

```yaml 
my_collection:
    type: str
    help: A collection of items
    choices: |
        {%- for my_item in items %}
        - {{my_item}}
        {%- endfor %}

``` 

And executed with

```python
run_copy(copier_loc, out_dir, data = { "items": ['a','b','c'] } )
```

I am happy to add it to the mkdocs markdown, but am unsure where it would best live. Just following the Jinja/Macro templates subheading possibly? https://copier.readthedocs.io/en/stable/configuring/#importing-jinja-templates-and-macros

### Desired Situation

More people are aware of the functionality. 

### Proposed solution

I add this to the documentation and it gets merged?

**Comment by wolfiex** [comment]
I would propose a similar solution to passing through a function and performing a conditional check: 

```yaml
iac:
    type: str
    help: Which IaC tool do you use?
    choices:
        Terraform: tf
        Cloud Formation:
            value: cf
            validator: "{% if not check_installed(cloud) %}Requires AWS{% endif %}"
```
