### ISSUE TITLE
Add a slugify filter

### ISSUE THREAD

**Issue by pawamoy** [copier-org/copier#208]
I cannot think of a template I wrote that didn't need such a filter 🙂 

I usually write a very naive one myself:

```yaml
repository_name:
  type: str
  help: Your repository name
  default: "[[ project_name|lower|replace('_', '-')|replace(' ', '-') ]]"
```

But it will break in so many cases.

As an alternative, if we don't want to support more and more filters in `copier`, maybe we could think of allowing custom filters to be used. Take a look at https://github.com/mattrobenolt/jinja2-cli/pull/86, it allows this use of `jinja2-cli`:

```
jinja2 -f ansible.plugins.filter.ipaddr.ipaddr test.txt
```

In `copier`'s case, we would not be able to load the filter using its Python dotted-path, so we would have to think of another way to add it to the Jinja environment.
