### ISSUE TITLE
Add _skip_tasks setting in copier.yml

### ISSUE THREAD

**Issue by EstebanMunoz** [copier-org/copier#2087]
### Actual Situation

Currently, the only way to avoid tasks execution is through the cli flag `-T`/`--skip-tasks`, but it is not possible to use a similar setting inside the `copier.yml` file. To be sure about this,  I have tried with `_skip_tasks: true` and `_skip_tasks: false` but none of them worked.

### Desired Situation

I have a template that builds a project using `_tasks` and I would like to run those tasks only when a certain condition is met. I know that is possible to add that condition using `when`, but it means I have to add the exact same condition to all of the tasks in the project. For that reason I find pretty useful the usage of `_skip_tasks` making it possible to disable all of them.

### Proposed solution

It would be nice to add the setting `_skip_tasks` and allow the use of the context to determine if its value is true or false. For example, I would like to build a project only if `build_project` is true.

**Comment by sisp** [comment]
How about using [YAML anchors and aliases](https://www.educative.io/blog/advanced-yaml-syntax-cheatsheet#YAML-Anchors-and-Alias)?

```yaml
_tasks:
  - command: ...
    when: &task_when "{{ condition }}"
  - command: ...
    when: *task_when
  - command: ...
    when: *task_when
```

This way, you define the `when` expression once in the first task and reuse it in all subsequent tasks.

**Comment by sisp** [comment]
Another option is to use a computed value:

```yaml
tasks_when:
  type: bool
  default: "{{ condition }}"
  when: false

_tasks:
  - command: ...
    when: "{{ tasks_when }}"
```

This is more flexible than YAML anchors and aliases, as you can have different composite `when` expressions for each tasks.
