### ISSUE TITLE
Skip directory if name is empty

### ISSUE THREAD

**Issue by jcantwell-JC** [copier-org/copier#216]
We are looking to have a configuration like this:

```
things:
  thing1:
    name: name1
    type: one
  thing2:
    name: name2
    type: one
  thing3:
    name: name3
    type: two
```

And from it we'd like to stamp out a particular folder for each `thing` based on its `type` field.  I'm wondering if any thought has been given to a feature like this?

One approach would be to support conditional directories.  If the name evaluates to empty, then omit it and all its content from being copied.   With this, its not ideal, but we could create a fixed number of folders:

```
- [[things.thing1.name if things.thing1 is not none]]
- [[things.thing2.name if things.thing2 is not none]]
... etc.  (I'm not 100% on that jijna syntax, but conceptually make the dir name empty if you don't want to render it).
```

Another approach would be somehow support `for` loops in directory names, but I'm uncertain of exactly how that might look right now.

Has this ever come up before?  Is there a feature or enhancement around this that `copier` would be willing to accept?

**Comment by pawamoy** [comment]
+1 on conditional files/directories (not rendered if the name is empty).

Copier does not support your first code block structure, however I'll be working on the conditional prompt feature soon, which means you would be able to do this instead:

```yaml
use_things:
  type: bool

thing1_name:
  type: str
  when: '[[ use_things ]]'

thing1_type:
  type: str
  when: '[[ use_things ]]'
```

At least this is the current proposal.

It's more verbose than a nested solution, but more flexible.
