### ISSUE TITLE
Add multiple choice prompt

### ISSUE THREAD

**Issue by baurmatt** [copier-org/copier#218]
#93/#107 implemented support for single choice questions. I'd love to see an option to use multiple choice prompts. Thinking about something like this:

```
ci_type:
  type: str
  help: Which CI configuration do you need?
  multiplechoice:
    - travis
    - circleci
    - gitlabci
    - jenkins
```

```
Which CI configuration do you need?
ci_type? Format: str
🎤
( ) travis
( ) circleci
( ) gitlabci
( ) jenkins
```

**Comment by Yajo** [comment]
A new prompt toolkit is planned in https://github.com/pykong/copier/issues/210 that might allow that. With our current toolkit, it's not possible.

However, that doesn't mean we will implement what you ask. Isn't using 4 boolean questions just good enough? :thinking: :

```yaml
# copier.yml
use_travis: yes
use_circleci: yes
use_gitlabci: yes
use_jenkins: yes
```

Your templating is going to be a lot easier too this way.
