### ISSUE TITLE
[bug] jinja templates not work in default section

### ISSUE THREAD

**Issue by misterkramer** [copier-org/copier#230]
Hi! Thanks for this cool project, but starting from version copier 4 the template functionality stopped working in default section

Example:
```
project_name:
  type: str
  help: Your project name
...
repository_name:
  type: str
  help: Your repository name
  default: "[[ project_name|lower|replace('_', '-')|replace(' ', '-') ]]"
```
Copier skips `repository_name` when generating a project.

In 3.2.0 this works.

Please, fix this error.
