### ISSUE TITLE
Jinja "[[ x ]]" in the default of a parameter y always reuses x's default (if it exists) regardless of user input to x

### ISSUE THREAD

**Issue by masda70** [copier-org/copier#309]
In `v6.0.0-a.5`, the following `copier.yml` always renders `email`'s default prompt as `foo@example.com` regardless of the input to the `username` and `organization` variables. In `v5.1.0`, `email` default prompt was based on the input to the `username` and `organization` variables.

```
# default
username:
    type: str
    default: "foo"

organization:
    type: str
    default: "example"

email:
    type: str
    # Notice that both `username` and `organization` have been already asked
    default: "[[ username ]]@[[ organization ]].com"
```

Additionally, if the default of `organization` is also a jinja template, `email`s default will not use the rendered `organization` default value.

**Comment by Yajo** [comment]
> Additionally, if the default of `organization` is also a jinja template, `email`s default will not use the rendered `organization` default value.

Would you be able to provide a `copier.yml` with such structure? Also some logs would help. I plan to add a test on this subject to ensure no more regressions happen.

Thanks for testing the alpha and for your report :blush:

**Comment by andrewleech** [comment]
Hi, I've run into this issue today testing a new setup with 6.0.0a6
With a really basic `copier.yaml`
``` yaml

username:
    type: str
    default: me

organization:
    type: str
    default: there

email:
    type: str
    # Notice that both `username` and `organization` have been already asked
    default: "[[ username ]]@[[ organization ]].com"

```
Running this without overriding the defaults results in expected behavior:
```
anl@STEP:~/test$ copier ../template .

No git tags found in template; using HEAD as ref
🎤 username? Format: str me
🎤 organization? Format: str there
🎤 email? Format: str me@there.com
```
However as reported, even when I overwrite the defaults at the prompt, they're still used in the templated default:
```
anl@STEP:~/test$ copier ../template .

No git tags found in template; using HEAD as ref
🎤 username? Format: str foo
🎤 organization? Format: str bar
🎤 email? Format: str me@there.com
Execution stopped by user
```

I had the same problem trying to use earlier variables in `where:` keys, the default is always provided by the variable, or `None` if no default is set.

**Comment by andrewleech** [comment]
Actually, this looks quite similar to https://github.com/copier-org/copier/issues/327 possibly it's already fixed. I'll have to give it a try on a master build.

**Comment by Yajo** [comment]
Ah nice thanks. Just pip install from git master and try, I'll wait for your report.

**Comment by andrewleech** [comment]
Thanks for the tip on pip install from master, for some reason I assumed it'd need an explicit build...

After updating the braces:
``` yaml
username:
    type: str
    default: me

organization:
    type: str
    default: there

email:
    type: str
    # Notice that both `username` and `organization` have been already asked
    default: "{{ username }}@{{ organization }}.com"

final:
    type: str
    # Notice that both `username` and `organization` have been already asked
    default: "Hello: {{ email }}"
```
Quick install into venv and run same test as before:
```
~/test$ python3 -m venv .venv
~/test$ .venv/bin/pip install git+https://github.com/copier-org/copier.git`
~/test$ .venv/bin/copier ../template .

No git tags found in template; using HEAD as ref
🎤 username? Format: str me
🎤 organization? Format: str there
🎤 email? Format: str me@there.com
🎤 final? Format: str Hello: me@there.com
Execution stopped by user

~test$ .venv/bin/copier ../ .

No git tags found in template; using HEAD as ref
🎤 username? Format: str you
🎤 organization? Format: str example
🎤 email? Format: str you@example.com
🎤 final? Format: str Hello: you@example.com
```

The problem as I saw it has been fixed perfectly already in maater thanks! 

@masda70 It'd be great if you could also confirm it's fixed for you?
