### ISSUE TITLE
Simplify migrations

### ISSUE THREAD

**Issue by yajo** [copier-org/copier#326]
The current migrations workflow is quite difficult to maintain.

The goal was to give full flexibility, but after some usage, it seems to make things more difficult.

Instead of having a migrations definition such as this:

```yaml

_migrations:
  - version: v1.0.0
    before:
      - &mig
        - "[[ _copier_conf.src_path / 'migrations.py' ]]"
        - "[[ _copier_conf|tojson ]]"
    after:
      - *mig
  - version: v2
    before: [*mig]
    after:
      - *mig
      - "rm delete-in-migration-$VERSION_CURRENT.txt"
```

We should be having something like this:

```yaml
_migrations:
  working_directory: "[[ _copier_conf.src_path ]]" # default value
  command: [poetry, run, migrations.py]
```

Then, all data needed for migrations will be passed as env variables, which that script can load and use to handle all of them comfortably.

At the end of the day, that code is easier to maintain in a migrations script, and this way we avoid the need to repeat the same definition once and again for each version (as seen in the 1st example using `*mig`).
