### ISSUE TITLE
Default answer from previous variable not being picked

### ISSUE THREAD

**Issue by joao-p-marques** [copier-org/copier#327]
Hi :wave: 

I am creating a template where I need to use one of the answers as a default for another question:
```yaml
# Questions
project_name:
  type: str
  help: The name of the project. This will also apply to the tags of the docker images built

project_owner:
  type: str
  help: The owner of the project. This will also apply to the tags of the docker images built

# [...]

dockerhub_id:
  type: str
  default: "{{ project_owner }}"
  when: "{{ push_to_dockerhub }}"
  help: If the image is going to be uploaded to DockerHub, what is the DockerId of the repository owner? (ignore if you are not going to push to DockerHub)
```
So, `dockerhub_id` should assume the default value of whatever `project_owner` is.

However, when running the template:
```bash
➤ copier copy /home/jota/Documents/Tecnativa/infra/image-template .
No git tags found in template; using HEAD as ref
🎤 The name of the project. This will also apply to the tags of the docker images built
project_name? Format: str test
🎤 The owner of the project. This will also apply to the tags of the docker images built
project_owner? Format: str Test

# [...]

dockerhub_id? Format: str None
```
As you can see, it doesn't assume the expected default value of 'Test', but it defaults to `None`.

I am running the version installed from `master`:
```
pipx install git+https://github.com/copier-org/copier.git
```
and, when I try the same config with copier 5, everything works as expected.
