### ISSUE TITLE
How to add a code-block depending on a condintion

### ISSUE THREAD

**Issue by incoggnito** [copier-org/copier#351]
Hey,

i don't know how to write the correct if-statement with jinja.
Here is the in my `copier.yml`:
```
special_place:
  type: bool
  help: Are you in a special_place?
  default: no
```
Here is a block i want to add to the `pyproject.toml.jinja`:

```
[% if  special_place %]
    [[tool.poetry.source]]
    name = "foo"
    url = "https://foo/repository/pypi/simple/"
    default = true
[% endif %]
```

It always tells me a "tool" UndifinedError... any recommendations?
