### ISSUE TITLE
bug: default boolean not displayed in questionnaire

### ISSUE THREAD

**Issue by RoyalTS** [copier-org/copier#396]
I have a variable defined in `copier.yml` like so:

```yaml
private:
  type: bool
  default: true
```

Yet, despite the default value being set that default value is not displayed in the questionnaire:

```sh
private? Format: bool
🎤? [Y/n]
```
