### ISSUE TITLE
feat: questionnaire validation

### ISSUE THREAD

**Issue by RoyalTS** [copier-org/copier#398]
I'd love a possibility to validate questionnaire inputs. Being able to validate `str` against regex would already be a huge help, e.g. by specifying a field appropriately in `copier.yml`:

```yaml
project_name:
  type: str
  help: Your project name
  validate: ^[a-zA-Z][_a-zA-Z0-9]+$
```
