### ISSUE TITLE
feat: Mulitple templates in one repo

### ISSUE THREAD

**Issue by xsc27** [copier-org/copier#430]
I would like to have a monolith repo for my templates. From what I can tell, each template must be in its own repo.

I would like to reference the templates in the subdirectories, i.e. 

```sh
copier copy git@github.com:USER/TEMPLATE-REPO/template1 new_repo1
```

Not that #412 has been resolved, my workaround is to checkout the repo first then point `copier` to the exact path. This is okay, but the few steps I can ask dev teams to do, the better. 😄

**Comment by Yajo** [comment]
You can just tell your devs to use:

```sh
copier copy git@github.com:USER/template1 new_repo1
```

Where `template1` is the one that's linked into your monorepo.

Another alternative is to let users choose the subdir by using a templated `_subdirectory`:

```yaml
# copier.yml
_subdirectory: "{{ subtemplate }}"
subtemplate:
  type: str
  choices:
    - template1
    - template2
```
