### ISSUE TITLE
bug: In newest version it is impossible to use jinja syntax

### ISSUE THREAD

**Issue by karolzlot** [copier-org/copier#432]
**Describe the problem**

In version 5.1 this worked:

copier.yml
```
_envops:
  block_end_string: "%}"
  block_start_string: "{%"
  comment_end_string: "#}"
  comment_start_string: "{#"
  keep_trailing_newline: true
  variable_end_string: "}}"
  variable_start_string: "{{"

```

In newest version I am getting error:
```
  File "C:\moje\programowanie\projekty2021_2\templates fastapi\fastapi-react\copier.yml", line 5, in template
    block_start_string: "{%"
jinja2.exceptions.TemplateSyntaxError: tag name expected
```

Not sure if it is not working by design or it is bug?

**Environment**
 - OS: Win10
 - Copier version: copier 6.0.0a6.post43.dev0+2fe3072
 - Python version: 3.9.6
 - Installation method: pipx+git
