### ISSUE TITLE
Do I use copier correctly ?

### ISSUE THREAD

**Issue by MadJlzz** [copier-org/copier#442]
Hello,

First time using `copier` here and I am facing a strange issue. Looking at the documentation, it seems pretty straightforward to configure a first template however I am really struggling to do it.

It is worth mentionning that I am trying to create a template out from an existing repository.

I've added a `copier.yaml` file at the root of my project that contains the following:
```yaml
# CONFIGURATION -------------------------
_subdirectory: project
_templates_suffix: .jinja

# PROMPT --------------------------------
project_name:
  type: str
  help: Your project name

project_description:
  type: str
  help: Your project description

author_fullname:
  type: str
  help: Your full name
  default: "Next Gate Tech"

author_email:
  type: str
  help: Your email
  default: "developers@nextgatetech.com"

repository_namespace:
  type: str
  help: Your repository namespace
  default: "next-gate-tech"

repository_name:
  type: str
  help: Your repository name
  default: "[[ project_name|lower|replace('_', '-')|replace(' ', '-') ]]"

python_package_distribution_name:
  type: str
  help: Your Python package distribution name (for `pip install NAME`)
  default: "[[ project_name|lower|replace('_', '-')|replace(' ', '-') ]]"
```

My root directory contains a `project` directory that contain itself the actual template.

What's weird is that whenever I run:
```bash
copier /k/sandbox/template /k/sandbox/generated-from-template
```
`copier` is copying everything from an older state of my project (feels like my `main` branch actually) even though I am doing the generation from my local filesystem. (and I am 100% sure being on the correct branch)

It doesn't even ask for the `inputs` present in the upper configuration file.

Is there some sort of cache?

I am working on Windows 10 with Python 3.9.6 64bits
