### ISSUE TITLE
bug: basic variable substitution not working

### ISSUE THREAD

**Issue by pkubat** [copier-org/copier#537]
**Describe the problem**
Newbie.. 
Basic template is not working.  variables are not substituted as expected.

I first tried using `{{project_name}}` as a directory named {{project_name}}, just like the example you have and it created a directory named {{project_name}} not the value but the actual text.

```
$ copier --version
copier 5.1.0
```

**Template**

copier.yml
```
# questions
username:
    type: str

organization:
    type: str

email:
    type: str
    # Notice that both `username` and `organization` have been already asked
    default: "{{ username }}@{{ organization }}.com"

project_name:
  type: str
  help: What is your project name?
  
project_slug:
  type: str
  help: Project directory (slug)?
  default: "{{project_name}}"
````

**To Reproduce**
```
$ copier template-service-node .

username? Format: str
🎤 [None]: SomeName

organization? Format: str
🎤 [None]: ThisCompany

email? Format: str
🎤 [{{ username }}@{{ organization }}.com]:
````

**Logs**

<details>

```

```

</details>

**Expected behavior**
 {{var}} to be replaced 

**Environment**
 - OS: macOS
 - Copier version: 5.1.0
 - Python version: 3.9.6 and also tried 3.10.1
 - Installation method:  pipx
