### ISSUE TITLE
`default` expression of skipped question is not evaluated

### ISSUE THREAD

**Issue by tpluscode** [copier-org/copier#589]
**Describe the problem**

I would like to have an always hidden question with a random integer value

**To Reproduce**

1. Add a question with `when: true` and an expression in `default`. For example
    ```yaml
    node_debug_port:
      when: false
      default: "{{ range(20000,65536) | random }}"
    ```
3. Generate from this template
4. `node_debug_port` will be taken at face value, its answer being
    ```yaml
    node_debug_port: "{{ range(20000,65536) | random }}"
    ```

**Expected behavior**

The jinja template should be evaluated, resulting in an entry in `.copier-answers.yaml` similar to

```yaml
node_debug_port: 56679
```

The expression is in fact evaluated when `when` is not false

**Environment**
 - OS: macOS Catalin
 - Copier version: 6.0.0a9
 - Python version: 3.9.10
 - Installation method: `pipx install "copier==6.0.0a9"`
