### ISSUE TITLE
If conditional directory does not match. Files are included Anyway

### ISSUE THREAD

**Issue by mbwhite** [copier-org/copier#634]
**Describe the problem**
If you have, for example, two conditional directories, and node of the if statements match, then the result is a directory with the files in both directories. 

**Template**
Project structure :

```
├── {% if language == 'java' %}javasrc{% endif %}
│   └── this is java.txt
├── {% if language == 'typescript' %}tssrc{% endif %}
│   └── this is typescript.txt
└── {{language}}.txt.jinja
```
**To Reproduce**
 - create the directory structure above
 - `copier.yaml` as follows
```
_min_copier_version: "5.1.0"
_subdirectory: project
_templates_suffix: .jinja
_envops:
  block_end_string: "%}"
  block_start_string: "{%"
  comment_end_string: "#}"
  comment_start_string: "{#"
  keep_trailing_newline: true
  variable_end_string: "}}"
  variable_start_string: "{{"
# questions
language:
  help: Which programming langauge to use
  choices: 
    - TypeScript
    - Java
```

Note that I've got the case of the languages different to the 'if' statements
This produces the output of

```
    create  Java.txt
    create  this is java.txt
    create  this is typescript.txt
```

When this is corrected in the `copier.yaml` and java is chosen
```
    create  java.txt
    create  javasrc/
    create  javasrc/this is java.txt
    create  this is typescript.txt
```

If typescript is chosen

```
    create  typescript.txt
    create  this is java.txt
    create  tssrc/
    create  tssrc/this is typescript.txt
```

**Environment**

 - OS: Ubuntu 20.04 (WSL2)
 - Copier version: 5.1.0
 - Python version: 3.8.10
 - Installation method: pipx
