### ISSUE TITLE
Default value of skipped questions end up in _copier_answers

### ISSUE THREAD

**Issue by verdaatt** [copier-org/copier#648]
**Describe the problem**

I've created a template that includes several questions with `default` set and a `when:` condition. If the condition resolves to `false` the question gets skipped, but the literal text default value gets included in `_copier_answers`anyway instead of omitted. This could have unexpected results.

Because the `default` value does not get interpreted this can cause additional issues when processed, like when jinja code is used in it, which is passed along literally and can get messed up when converted to yaml formatting.

**Template**

**copier.yaml**

```yaml
_min_copier_version: 6.0.0a9

name:
  type: str
  default: problem

condition:
  type: bool
  default: false

options:
  type: str
  choices:
    - option-one
    - option-two
    - option-three
    - option-four

problem:
  type: str
  when: "{{ condition }}"
  default: "my-{{ options | replace('option-one', 'first') | replace('option-two', 'second') | replace('option-three', 'third') | replace('option-four', 'fourth') }}-{{ name | lower }}-example"

whatever:
  type: str
  default: indeed
```

**{{_copier_conf.answers_file}}.jinja**

```jinja
{{ _copier_answers | to_nice_yaml }}
```

**.copier-answers.yml**

```yaml
# Changes here will be overwritten by Copier
_src_path: .
condition: false
name: problem
options: option-two
problem: my-{{ options | replace('option-one', 'first') | replace('option-two', 'second')
    | replace('option-three', 'third') | replace('option-four', 'fourth') }}-{{ name
    | lower }}-example
whatever: indeed
```

**To Reproduce**

1. extract [issue.zip](https://github.com/copier-org/copier/files/8531613/issue.zip)
2. Run `copier --data name=problem --data condition=false --data options=option-two --data whatever=indeed . ./result`
5. See `.copier-answers.yml`

**Logs**

None

**Expected behavior**

The questions that are skipped due to their `when:` resolving to `false` do not get added to the `_copier_answers` array.

**Screenshots/screencasts/logs**

**Environment**
 - OS: Linux
 - Copier version: 6.0.0a9
 - Python version: 3.8.10
 - Installation method: pip

**Additional context**

None
