### ISSUE TITLE
Shared variables

### ISSUE THREAD

**Issue by punkstarman** [copier-org/copier#716]
In order to factor out common calculations, especially amongst file and directory names, it would be useful to be able to define variables in `copier.yml` whose values are calculated based on answers or other variables.

For example, when creating a template for a Java project, based on the name of the project, I would like to calculate the name of the root package, and also the path of the root package.

```yaml
project_name:
  type: str
  default: hello-world

root_package:
  type: str
  default: "org.example.{{ project_name | title | regex_replace('-', '.') }}"

root_package_dir:
  type: str
  default: "{{ root_package | regex_replace('.', '/') }}"
```

The root package variable would be referred to by multiple files.

The root package directory must be calculated this way since you cannot have a filename with a slash (`/`).

**Describe the solution you'd like**
I suggest adding support for defining variables in `copier.yml` in a similar way as defining questions. The two are distinguished in some way, perhaps by a prefix such as a double underscore (`__`) or by a key such as `hidden: true`. I suggest that it be possible to mix defining variables and questions such that a question definition can refer to prior variables.

**Describe alternatives you've considered**
This feature is called [Private Variables in Cookicutter](https://cookiecutter.readthedocs.io/en/stable/advanced/private_variables.html).

An obvious workaround is to define questions with default values. This is unsatisfactory because this forces users to read the trivial question and decide to hit the enter key, which adds unnecessary overhead and 

**Additional context**
The given example refers to Java, but templates for other programming languages, including Python, could have similar issues.
