### ISSUE TITLE
Add intro message

### ISSUE THREAD

**Issue by lhupfeldt** [copier-org/copier#723]
I would like a clean way to display an intro message before the input questions.
Right now I'm doing this by adding it to the first question.
There are a couple og potentional problems with this:
- An argument gets added before the first argument, causing the intro message to be display after the first question
- It is not possible to programmatically use the intro message, e.g. for a UI.

I suggest adding an `intro_message` configuration item.
Or maybe `pre_message`, `post_success_message`, `post_fail_message`?

**Comment by pawamoy** [comment]
Side note: I've succesfully added a post-generation message ("thank you for using our template blablabla") using a task 🙂

**Comment by lhupfeldt** [comment]
> Is the finish message really needed, or just a "by the way"?

The finish messages were "by the way" :)

**Comment by lhupfeldt** [comment]
And I agree that an exception should not be hidden, so a `post` message should not be a replacement for the exception message/stacktrace.
The nice thing about declared post message vs printing from a task would be easy UI integration.
But I guess it could be added later if someone need it.

**Comment by sisp** [comment]
How about the following extension to `copier.yml`?

- For plain text:

    ```yaml
    _message: "Project {{ project_name }} successully created! 🎉"
    ```

- For inline Markdown (we could use [`rich`](https://github.com/Textualize/rich) to render it in the terminal :heart_eyes:):

    ```yaml
    _message: |
      # Next steps

      Project {{ project_name }} successfully generated! 🎉

      This is what you should do next:

      1. ...
      2. ...
    ```

- For including an external file (plain text or Markdown), we can use a [Jinja include](https://copier.readthedocs.io/en/v8.0.0/configuring/#importing-jinja-templates-and-macros):

    ```yaml
    _message: "{% include 'path/to/message.md.jinja' %}"
    ```

In fact, I suggest to always treat the message as Markdown and render it. When it's "plain text", there is no difference.

We should distinguish between a post-copy and a post-update message. This could be achieved through a new Jinja variable such as `_copier_conf.action: Literal["copy", "update"]`. For instance:

```yaml
_message: "Project {{ project_name }} successully {{ _copier_conf.action == 'copy' | ternary('created', 'updated') }}! 🎉"
```

WDYT, @copier-org/maintainers and @lhupfeldt?

**Comment by pawamoy** [comment]
Note that when updating, the `copy` message might be displayed before the `update` one, and not *instead* of, though that's coming from tasks, so maybe a tighter integration can take better care of that.

Other than that I like your suggestions @sisp :slightly_smiling_face:

**Comment by sisp** [comment]
> Note that when updating, the `copy` message might be displayed before the `update` one, and not _instead_ of, though that's coming from tasks, so maybe a tighter integration can take better care of that.

I'm not sure I understand what you mean. :thinking: Are you referring to a message printed by task?

> Other than that I like your suggestions @sisp slightly_smiling_face `_message` here though is only for post-copy/update, right? What about the intro message originally asked in this ticket?

Yes, it's only for post-copy/update. I hadn't noticed that the original question about a message _before_ the first question gets asked :facepalm: as much of the discussion later was about a finish message. Now that I do, I wonder about the value of an _intro_ message. :thinking: Unless Copier pauses and the user needs to press some button to continue, would anybody actually notice an intro message (unless it's huge)?

My use case is to print next steps instructions after successful project creation/updating that depend on the answers of some of the questions.

**Comment by sisp** [comment]
Thanks for the clarification! :+1: Yes, a tighter integration should be able to control the printing better.

There's actually another point about message printing. Should the `-q, --quiet` flag suppress those messages?

Thanks for the intro message example, I see how this might be useful now. :+1: How about supporting both intro and finish post-copy/update messages in the same way? Here are a few ideas for new syntax:

```yaml
_message:
  start: ...
  finish: ...

_message:
  start: ...
  end: ...

_message:
  opening: ...
  closing: ...

_message:
  introduction: ...
  conclusion: ...

_message:
  preface: ...
  postface: ...

_message:
  preamble: ...
  end: ...

_message:
  prolog: ...
  epilog: ...

_message:
  welcome: ...
  goodbye: ...

_message:
  hello: ...
  bye: ...
```

**Comment by pawamoy** [comment]
I think I like preamble/end the most :slightly_smiling_face:

**Comment by yajo** [comment]
We can have 4 to cover all scenarios:

```yaml
_message_before_copy: Hello, welcome...
_message_after_copy: I hope you liked it. Now do this and that
_message_before_update: It looks like you're updating. Beware, this version includes a breaking change. Blah blah.
_message_after_update: Done, friend. Now pay me 1 million dollars or run `git reset --hard`
```

If you add it like this, just with `_message_before_copy` we're done fixing this issue; but you'd leave room for others to come later.

BTW, splitting into different configs might look ugly, but makes usage of `!include` more capable.
