### ISSUE TITLE
Add support for nested prompts

### ISSUE THREAD

**Issue by sisp** [copier-org/copier#751]
**Is your feature request related to a problem? Please describe.**
I'd like to include zero or more custom PyPI source URLs and optional authentication credentials in a generated Python project (the credentials would be processed by a Copier task after successful project generation). If I were only trying to add _zero or **one**_ of those PyPIs, I could handle it with the currently available prompt types, but with _zero or **more**_ it's more involved. Handling multiple repeated prompts is a separate topic I've raised in #750 already. If that proposal gets accepted, I believe it would be necessary to support nested prompts for this use case whose answers are gathered in a Python `dict`. But nested prompts might also be useful on their own in order to group related answers.

**Describe the solution you'd like**
I imagine a solution could look like this (where the `multiple` field is taken from the proposal in #750):
```yaml
pypi_sources:
  type: struct  # or `dict`/`map`/`nested`/...
  help: Add custom PyPI sources
  fields:
    url:
      type: str
      help: Custom PyPI source URL
    auth:
      type: bool
      help: Requires authentication?
      default: yes
    auth_username:
      type: str
      help: Username
      when: "{% if pypi_sources|last|attr('auth') %}true{% endif %}"
    auth_password:
      type: str
      help: Password
      when: "{% if pypi_sources|last|attr('auth') %}true{% endif %}"
      secret: true
  multiple: true
```

The answers of the nested prompts would be gathered in a Python `dict`. The validation expression, when present, would be executed after every input with the current dict of answers. For validating each field independently, the field must be selected explicitly to avoid possible name collisions in the accessible Jinja context, e.g. `pypi_sources|last|attr('url')` for validating the just entered URL. This way, complex validation logic that depends on previously entered answers would be possible, too.

Deep nesting would be possible but should probably be avoided to keep the questionnaire simple. Regarding UX, perhaps the nesting could be visualized using Unicode art similar to how the `tree` tool prints filesystem trees:

```
🎤 Add custom PyPI sources
├─┬─ 🎤 Custom PyPI source URL
│ │     https://gitlab.com/api/v4/groups/<group_id_1>/-/packages/pypi/simple
│ ├─ 🎤 Requires authentication?
│ │     Yes
│ ├─ 🎤 Username
│ │     sisp
│ └─ 🎤 Password
│       ********
└─┬─ 🎤 Custom PyPI source URL
  │     https://gitlab.com/api/v4/groups/<group_id_2>/-/packages/pypi/simple
  └─ 🎤 Requires authentication?
        [Y/n]
```

**Describe alternatives you've considered**
Alternatively, a `type: yaml` or `type: json` prompt could be used, but the flow would not be guided, so the UX would be worse. Also, validation logic would be more complex.

**Additional context**
I'd be happy to work on a PR if this proposal gets accepted.
