### ISSUE TITLE
Formalize copier.yml schema (or use JSON schema)

### ISSUE THREAD

**Issue by bollwyvl** [copier-org/copier#918]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to validate a `copier.yml` without loading it in copier.

**Describe the solution you'd like**

Create a normalized, versioned JSON schema, checked into the repo, and available for tools. It could be authored in yaml, but having it checked in as actual JSON, somewhere, is important for downstreams.

Use this as an up-front validator when parsing a file.

**Describe alternatives you've considered**

Optionally, allow opting a `copier.yml` into being a JSON Schema itself, as there is already robust tooling for this in many languages. A number of features (`oneOf`, `default`) are already handled by JSON schema. Templating (though conditionals schema, `if`, and other things are possible).

**Additional context**

**Comment by sisp** [comment]
I've actually been thinking about something similar a while ago. I was looking for IDE autocompletion for `copier.yml` in VS Code which can be done via JSON schema.

Copier uses [Pydantic](https://github.com/pydantic/pydantic) in some places although (I think) a bit inconsistently. I've quietly been working on refactoring the [`user_data.Question`](https://github.com/copier-org/copier/blob/f8ae8d6e8ed8ec5333abe4b20ad53bc87123bff0/copier/user_data.py#L142-L414) class into several Pydantic models to get a proper/detailed domain model of the `copier.yml` content (which may still contain Jinja templates) as well as the rendered content. The Pydantic model of the `copier.yml` file could then be used to validated the file upon loading it into Copier, and it can also be used to generate a [JSON schema](https://docs.pydantic.dev/usage/schema/), making it the single source of truth.

What I've been working on doesn't work yet although I've come quite far already. When I've made enough progress, I'll send a PR, but I can't provide a timeline.

**Comment by bollwyvl** [comment]
Yeah, pydantic is... fine. But indeed, the language servers definitely like proper schema, so actually shipping and using a versioned schema at runtime is useful in its own right. 

But, having schema exist external to Pydantic has certain benefits, such as being able to use [hypothesis-jsonschema](https://github.com/python-jsonschema/hypothesis-jsonschema) to _test_ the pydantic implementation. And pydantic has some... quirks in its generation of schema, for sure. 

Having been down the "iteratively apply schema for templated yaml" (and/or, the much worse YAML tagged/magic comment): there's not a lot you can do but intercept right after `(ruamel_)yaml.(safe_)load`.

There's also some prior (but uncoordinated) art for _heavy_ usage of the above patterns, such as:
- [ansible-lsp](https://github.com/ansible/ansible-language-server)
- [salt-lsp](https://github.com/dcermak/salt-lsp)

But again: having an (alternate) input that actually _is_ JSON schema (or something that generates a JSON schema _of_ a template) would allow for reusing many existing tools, both for template authors or template users. For example, I've wrapped the [cookiecutter-almost-schema](https://github.com/deathbeds/jupyterlab-starters/blob/master/src/jupyter_starters/py_starters/cookiecutter.py#L283), and it works... pretty well. Looking to do so for copier as well!

**Comment by sisp** [comment]
Yes, Pydantic is certainly not perfect at the moment. The core team is working on v2 with many improvements though.

For REST/HTTP API development, I'm a big fan of writing the OpenAPI schema explicitly (i.e. spec-first approach) rather than using, e.g., Pydantic that can generate the schema/spec for me. But with the increasing of adoption of type hints in Python, I think there's some merit in using Pydantic because Pydantic models are (typically) properly typed. If a JSON schema is written manually, then Python types either need to be written (and kept in sync) manually or generated (which still lacks good tools, I think).

**Comment by rafalkrupinski** [comment]
How about this for starters?

Definitely not perfect, I've only worked with openapi 3 so far.

```yaml
$schema: "https://json-schema.org/draft/2020-12/schema"
$id: "https://example.com/product.schema.json"
title: Copier config
type: object
properties:
  _exclude:
    type: array
    items:
      type: string
  _answers_file:
    type: string
  _envops:
    type: object
  _jinja_extensions:
    type: array
    items:
      type: string
  _min_copier_version:
    type: string
  _secret_questions:
    type: array
    items:
      type: string
  _skip_if_exists:
    type: array
    items:
      type: string
  _subdirectory:
    type: string
  _migrations:
    type: array
    items:
      type: object
      properties:
        version:
          type: string
        before:
          type: array
          items:
            type: string
        after:
          type: array
          items:
            type: string
  _templates_suffix:
    type: string
    default: .jinja
additionalProperties:
  oneOf:
  - type: string
  - type: object
    properties:
      type:
        type: string
        enum:
        - bool
        - float
        - int
        - json
        - string
        - yaml
        default: yaml
      help:
        type: string
      choices:
        type: array
        items:
          type: object
      default: {}
      secret:
        type: boolean
      placeholder: {}
      multiline:
        type: bool
        default: false
      validator:
        type: string
      when:
        type: string
    additionalProperties: false
```
